services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: proxy-smart-keycloak-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: INFO
      # Allow CORS for development
      KC_HOSTNAME: localhost
      KC_HOSTNAME_URL: http://localhost:8080
      # PostgreSQL database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start-dev
      - --import-realm
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - proxy-smart

  postgres:
    image: postgres:16-alpine
    container_name: proxy-smart-postgres-dev
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./keycloak/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - proxy-smart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.mono
    container_name: proxy-smart-app-dev
    environment:
      NODE_ENV: development
      PORT: 8445
      BASE_URL: http://localhost:8445
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_DOMAIN: localhost
      KEYCLOAK_REALM: proxy-smart
      KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/proxy-smart/protocol/openid-connect/certs
      KEYCLOAK_ADMIN_CLIENT_ID: admin-service
      KEYCLOAK_ADMIN_CLIENT_SECRET: admin-service-secret
      FHIR_SERVER_BASE: https://hapi.fhir.org/baseR4,https://server.fire.ly # Multiple FHIR servers can be specified, separated by commas
      # UI is served from /webapp path by the backend
      VITE_API_BASE_URL: http://localhost:8445
      VITE_BASE: /webapp/
      # Allow CORS from multiple origins for development
      CORS_ORIGINS: http://localhost:8445,http://localhost:5173,http://localhost:3000,http://127.0.0.1:8445
    ports:
      - "8445:8445"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - proxy-smart
    # For development, you might want to add volume mounts for hot reloading
    # volumes:
    #   - ./backend/src:/app/backend/src
    #   - ./ui/src:/app/ui/src

volumes:
  postgres_data_dev:
    name: proxy-smart-postgres-data-dev

networks:
  proxy-smart:
    name: proxy-smart-network-dev
    driver: bridge
