# fly.toml app configuration file generated for proxy-smart-alpha-auth on 2025-08-07T20:19:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proxy-smart-alpha-auth'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile.keycloak'

[env]
  KC_DB = 'postgres'
  KC_DB_URL = 'jdbc:postgresql://proxy-smart-alpha-db.flycast:5432/postgres?sslmode=disable'
  KC_DB_USERNAME = 'postgres'
  KC_DB_PASSWORD = 'alphapassword123'
  KC_HEALTH_ENABLED = 'true'
  KC_HOSTNAME_STRICT = 'false'
  KC_HTTP_ENABLED = 'true'
  KC_METRICS_ENABLED = 'true'
  KC_PROXY = 'edge'
  KC_PROXY_HEADERS = 'xforwarded'
  KC_HOSTNAME = 'proxy-smart-alpha-auth.fly.dev'
  KC_HOSTNAME_URL = 'https://proxy-smart-alpha-auth.fly.dev'
  KC_HOSTNAME_ADMIN_URL = 'https://proxy-smart-alpha-auth.fly.dev'
  KEYCLOAK_ADMIN = 'admin'
  KEYCLOAK_ADMIN_PASSWORD = 'admin'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

[[vm]]
  size = 'shared-cpu-4x'
  memory = '4096mb'
