app = "proxy-smart-alpha"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.mono"

[env]
  NODE_ENV = "alpha"
  BASE_URL = "https://proxy-smart-alpha.fly.dev"
  FHIR_SERVER_BASE = "https://hapi.fhir.org/baseR4"
  KEYCLOAK_BASE_URL = "https://proxy-smart-alpha-auth.fly.dev"
  KEYCLOAK_REALM = "proxy-smart"
  PORT = "8445"
  CORS_ORIGINS = "https://proxy-smart-alpha.fly.dev"

[[services]]
  internal_port = 8445
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/health"

[vm]
  size = "shared-cpu-1x"
  memory = "1024mb"
