/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdminFhirGroupsByGroupIdMembers200ResponseInner
 */
export interface GetAdminFhirGroupsByGroupIdMembers200ResponseInner {
    /**
     * User ID
     * @type {string}
     * @memberof GetAdminFhirGroupsByGroupIdMembers200ResponseInner
     */
    userId: string;
    /**
     * Username
     * @type {string}
     * @memberof GetAdminFhirGroupsByGroupIdMembers200ResponseInner
     */
    username: string;
    /**
     * First name
     * @type {string}
     * @memberof GetAdminFhirGroupsByGroupIdMembers200ResponseInner
     */
    firstName?: string;
    /**
     * Last name
     * @type {string}
     * @memberof GetAdminFhirGroupsByGroupIdMembers200ResponseInner
     */
    lastName?: string;
    /**
     * Email address
     * @type {string}
     * @memberof GetAdminFhirGroupsByGroupIdMembers200ResponseInner
     */
    email?: string;
    /**
     * FHIR reference for the user
     * @type {string}
     * @memberof GetAdminFhirGroupsByGroupIdMembers200ResponseInner
     */
    fhirReference?: string;
}

/**
 * Check if a given object implements the GetAdminFhirGroupsByGroupIdMembers200ResponseInner interface.
 */
export function instanceOfGetAdminFhirGroupsByGroupIdMembers200ResponseInner(value: object): value is GetAdminFhirGroupsByGroupIdMembers200ResponseInner {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function GetAdminFhirGroupsByGroupIdMembers200ResponseInnerFromJSON(json: any): GetAdminFhirGroupsByGroupIdMembers200ResponseInner {
    return GetAdminFhirGroupsByGroupIdMembers200ResponseInnerFromJSONTyped(json, false);
}

export function GetAdminFhirGroupsByGroupIdMembers200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminFhirGroupsByGroupIdMembers200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'username': json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'fhirReference': json['fhirReference'] == null ? undefined : json['fhirReference'],
    };
}

export function GetAdminFhirGroupsByGroupIdMembers200ResponseInnerToJSON(json: any): GetAdminFhirGroupsByGroupIdMembers200ResponseInner {
    return GetAdminFhirGroupsByGroupIdMembers200ResponseInnerToJSONTyped(json, false);
}

export function GetAdminFhirGroupsByGroupIdMembers200ResponseInnerToJSONTyped(value?: GetAdminFhirGroupsByGroupIdMembers200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'fhirReference': value['fhirReference'],
    };
}

