/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAuthUserinfo401Response
 */
export interface GetAuthUserinfo401Response {
    /**
     * Error message
     * @type {string}
     * @memberof GetAuthUserinfo401Response
     */
    error: string;
}

/**
 * Check if a given object implements the GetAuthUserinfo401Response interface.
 */
export function instanceOfGetAuthUserinfo401Response(value: object): value is GetAuthUserinfo401Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetAuthUserinfo401ResponseFromJSON(json: any): GetAuthUserinfo401Response {
    return GetAuthUserinfo401ResponseFromJSONTyped(json, false);
}

export function GetAuthUserinfo401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAuthUserinfo401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function GetAuthUserinfo401ResponseToJSON(json: any): GetAuthUserinfo401Response {
    return GetAuthUserinfo401ResponseToJSONTyped(json, false);
}

export function GetAuthUserinfo401ResponseToJSONTyped(value?: GetAuthUserinfo401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

