/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealth503Response
 */
export interface GetHealth503Response {
    /**
     * Health status
     * @type {string}
     * @memberof GetHealth503Response
     */
    status: string;
    /**
     * Current timestamp
     * @type {string}
     * @memberof GetHealth503Response
     */
    timestamp: string;
    /**
     * Error description
     * @type {string}
     * @memberof GetHealth503Response
     */
    error: string;
    /**
     * Error details
     * @type {any}
     * @memberof GetHealth503Response
     */
    details?: any | null;
}

/**
 * Check if a given object implements the GetHealth503Response interface.
 */
export function instanceOfGetHealth503Response(value: object): value is GetHealth503Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetHealth503ResponseFromJSON(json: any): GetHealth503Response {
    return GetHealth503ResponseFromJSONTyped(json, false);
}

export function GetHealth503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': json['timestamp'],
        'error': json['error'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function GetHealth503ResponseToJSON(json: any): GetHealth503Response {
    return GetHealth503ResponseToJSONTyped(json, false);
}

export function GetHealth503ResponseToJSONTyped(value?: GetHealth503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'],
        'error': value['error'],
        'details': value['details'],
    };
}

