/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServerInfo500Response
 */
export interface GetServerInfo500Response {
    /**
     * Error message
     * @type {string}
     * @memberof GetServerInfo500Response
     */
    error: string;
    /**
     * Error code
     * @type {string}
     * @memberof GetServerInfo500Response
     */
    code?: string;
    /**
     * Additional error details
     * @type {any}
     * @memberof GetServerInfo500Response
     */
    details?: any | null;
}

/**
 * Check if a given object implements the GetServerInfo500Response interface.
 */
export function instanceOfGetServerInfo500Response(value: object): value is GetServerInfo500Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetServerInfo500ResponseFromJSON(json: any): GetServerInfo500Response {
    return GetServerInfo500ResponseFromJSONTyped(json, false);
}

export function GetServerInfo500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServerInfo500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function GetServerInfo500ResponseToJSON(json: any): GetServerInfo500Response {
    return GetServerInfo500ResponseToJSONTyped(json, false);
}

export function GetServerInfo500ResponseToJSONTyped(value?: GetServerInfo500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'code': value['code'],
        'details': value['details'],
    };
}

