/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetServerInfo200ResponseServerInfo
 */
export interface GetServerInfo200ResponseServerInfo {
    /**
     * Actual FHIR version supported by server
     * @type {string}
     * @memberof GetServerInfo200ResponseServerInfo
     */
    fhirVersion: string;
    /**
     * Server software version
     * @type {string}
     * @memberof GetServerInfo200ResponseServerInfo
     */
    serverVersion?: string;
    /**
     * Server software name
     * @type {string}
     * @memberof GetServerInfo200ResponseServerInfo
     */
    serverName?: string;
    /**
     * Whether this version is supported by our proxy
     * @type {boolean}
     * @memberof GetServerInfo200ResponseServerInfo
     */
    supported: boolean;
}

/**
 * Check if a given object implements the GetServerInfo200ResponseServerInfo interface.
 */
export function instanceOfGetServerInfo200ResponseServerInfo(value: object): value is GetServerInfo200ResponseServerInfo {
    if (!('fhirVersion' in value) || value['fhirVersion'] === undefined) return false;
    if (!('supported' in value) || value['supported'] === undefined) return false;
    return true;
}

export function GetServerInfo200ResponseServerInfoFromJSON(json: any): GetServerInfo200ResponseServerInfo {
    return GetServerInfo200ResponseServerInfoFromJSONTyped(json, false);
}

export function GetServerInfo200ResponseServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServerInfo200ResponseServerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'fhirVersion': json['fhirVersion'],
        'serverVersion': json['serverVersion'] == null ? undefined : json['serverVersion'],
        'serverName': json['serverName'] == null ? undefined : json['serverName'],
        'supported': json['supported'],
    };
}

export function GetServerInfo200ResponseServerInfoToJSON(json: any): GetServerInfo200ResponseServerInfo {
    return GetServerInfo200ResponseServerInfoToJSONTyped(json, false);
}

export function GetServerInfo200ResponseServerInfoToJSONTyped(value?: GetServerInfo200ResponseServerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fhirVersion': value['fhirVersion'],
        'serverVersion': value['serverVersion'],
        'serverName': value['serverName'],
        'supported': value['supported'],
    };
}

