/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetVByFhirReleaseFhirServerInfo200ResponseServerInfo } from './GetVByFhirReleaseFhirServerInfo200ResponseServerInfo';
import {
    GetVByFhirReleaseFhirServerInfo200ResponseServerInfoFromJSON,
    GetVByFhirReleaseFhirServerInfo200ResponseServerInfoFromJSONTyped,
    GetVByFhirReleaseFhirServerInfo200ResponseServerInfoToJSON,
    GetVByFhirReleaseFhirServerInfo200ResponseServerInfoToJSONTyped,
} from './GetVByFhirReleaseFhirServerInfo200ResponseServerInfo';

/**
 * 
 * @export
 * @interface GetVByFhirReleaseFhirServerInfo200Response
 */
export interface GetVByFhirReleaseFhirServerInfo200Response {
    /**
     * Requested FHIR version
     * @type {string}
     * @memberof GetVByFhirReleaseFhirServerInfo200Response
     */
    requestedVersion: string;
    /**
     * 
     * @type {GetVByFhirReleaseFhirServerInfo200ResponseServerInfo}
     * @memberof GetVByFhirReleaseFhirServerInfo200Response
     */
    serverInfo: GetVByFhirReleaseFhirServerInfo200ResponseServerInfo;
    /**
     * Whether the requested version matches server version
     * @type {boolean}
     * @memberof GetVByFhirReleaseFhirServerInfo200Response
     */
    supported: boolean;
}

/**
 * Check if a given object implements the GetVByFhirReleaseFhirServerInfo200Response interface.
 */
export function instanceOfGetVByFhirReleaseFhirServerInfo200Response(value: object): value is GetVByFhirReleaseFhirServerInfo200Response {
    if (!('requestedVersion' in value) || value['requestedVersion'] === undefined) return false;
    if (!('serverInfo' in value) || value['serverInfo'] === undefined) return false;
    if (!('supported' in value) || value['supported'] === undefined) return false;
    return true;
}

export function GetVByFhirReleaseFhirServerInfo200ResponseFromJSON(json: any): GetVByFhirReleaseFhirServerInfo200Response {
    return GetVByFhirReleaseFhirServerInfo200ResponseFromJSONTyped(json, false);
}

export function GetVByFhirReleaseFhirServerInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVByFhirReleaseFhirServerInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'requestedVersion': json['requestedVersion'],
        'serverInfo': GetVByFhirReleaseFhirServerInfo200ResponseServerInfoFromJSON(json['serverInfo']),
        'supported': json['supported'],
    };
}

export function GetVByFhirReleaseFhirServerInfo200ResponseToJSON(json: any): GetVByFhirReleaseFhirServerInfo200Response {
    return GetVByFhirReleaseFhirServerInfo200ResponseToJSONTyped(json, false);
}

export function GetVByFhirReleaseFhirServerInfo200ResponseToJSONTyped(value?: GetVByFhirReleaseFhirServerInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestedVersion': value['requestedVersion'],
        'serverInfo': GetVByFhirReleaseFhirServerInfo200ResponseServerInfoToJSON(value['serverInfo']),
        'supported': value['supported'],
    };
}

