/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAuthTokenRequest
 */
export interface PostAuthTokenRequest {
    /**
     * OAuth grant type (e.g., authorization_code, client_credentials)
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    grantType: string;
    /**
     * Authorization code for exchange
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    code?: string;
    /**
     * Redirect URI for authorization code flow
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    redirectUri?: string;
    /**
     * OAuth client ID
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    clientId?: string;
    /**
     * OAuth client secret
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    clientSecret?: string;
    /**
     * PKCE code verifier for security
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    codeVerifier?: string;
    /**
     * Refresh token for refresh_token grant
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    refreshToken?: string;
    /**
     * Requested scopes
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    scope?: string;
    /**
     * Audience for the token request
     * @type {string}
     * @memberof PostAuthTokenRequest
     */
    audience?: string;
}

/**
 * Check if a given object implements the PostAuthTokenRequest interface.
 */
export function instanceOfPostAuthTokenRequest(value: object): value is PostAuthTokenRequest {
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    return true;
}

export function PostAuthTokenRequestFromJSON(json: any): PostAuthTokenRequest {
    return PostAuthTokenRequestFromJSONTyped(json, false);
}

export function PostAuthTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'grantType': json['grant_type'],
        'code': json['code'] == null ? undefined : json['code'],
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'codeVerifier': json['code_verifier'] == null ? undefined : json['code_verifier'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'audience': json['audience'] == null ? undefined : json['audience'],
    };
}

export function PostAuthTokenRequestToJSON(json: any): PostAuthTokenRequest {
    return PostAuthTokenRequestToJSONTyped(json, false);
}

export function PostAuthTokenRequestToJSONTyped(value?: PostAuthTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grant_type': value['grantType'],
        'code': value['code'],
        'redirect_uri': value['redirectUri'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'code_verifier': value['codeVerifier'],
        'refresh_token': value['refreshToken'],
        'scope': value['scope'],
        'audience': value['audience'],
    };
}

