/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAdminFhirGroupsRequestMemberInnerPeriod } from './PostAdminFhirGroupsRequestMemberInnerPeriod';
import {
    PostAdminFhirGroupsRequestMemberInnerPeriodFromJSON,
    PostAdminFhirGroupsRequestMemberInnerPeriodFromJSONTyped,
    PostAdminFhirGroupsRequestMemberInnerPeriodToJSON,
    PostAdminFhirGroupsRequestMemberInnerPeriodToJSONTyped,
} from './PostAdminFhirGroupsRequestMemberInnerPeriod';
import type { PostAdminFhirGroupsRequestMemberInnerEntity } from './PostAdminFhirGroupsRequestMemberInnerEntity';
import {
    PostAdminFhirGroupsRequestMemberInnerEntityFromJSON,
    PostAdminFhirGroupsRequestMemberInnerEntityFromJSONTyped,
    PostAdminFhirGroupsRequestMemberInnerEntityToJSON,
    PostAdminFhirGroupsRequestMemberInnerEntityToJSONTyped,
} from './PostAdminFhirGroupsRequestMemberInnerEntity';

/**
 * 
 * @export
 * @interface PostAdminFhirGroupsRequestMemberInner
 */
export interface PostAdminFhirGroupsRequestMemberInner {
    /**
     * 
     * @type {PostAdminFhirGroupsRequestMemberInnerEntity}
     * @memberof PostAdminFhirGroupsRequestMemberInner
     */
    entity: PostAdminFhirGroupsRequestMemberInnerEntity;
    /**
     * 
     * @type {PostAdminFhirGroupsRequestMemberInnerPeriod}
     * @memberof PostAdminFhirGroupsRequestMemberInner
     */
    period?: PostAdminFhirGroupsRequestMemberInnerPeriod;
    /**
     * Whether the member is inactive
     * @type {boolean}
     * @memberof PostAdminFhirGroupsRequestMemberInner
     */
    inactive?: boolean;
}

/**
 * Check if a given object implements the PostAdminFhirGroupsRequestMemberInner interface.
 */
export function instanceOfPostAdminFhirGroupsRequestMemberInner(value: object): value is PostAdminFhirGroupsRequestMemberInner {
    if (!('entity' in value) || value['entity'] === undefined) return false;
    return true;
}

export function PostAdminFhirGroupsRequestMemberInnerFromJSON(json: any): PostAdminFhirGroupsRequestMemberInner {
    return PostAdminFhirGroupsRequestMemberInnerFromJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestMemberInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminFhirGroupsRequestMemberInner {
    if (json == null) {
        return json;
    }
    return {
        
        'entity': PostAdminFhirGroupsRequestMemberInnerEntityFromJSON(json['entity']),
        'period': json['period'] == null ? undefined : PostAdminFhirGroupsRequestMemberInnerPeriodFromJSON(json['period']),
        'inactive': json['inactive'] == null ? undefined : json['inactive'],
    };
}

export function PostAdminFhirGroupsRequestMemberInnerToJSON(json: any): PostAdminFhirGroupsRequestMemberInner {
    return PostAdminFhirGroupsRequestMemberInnerToJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestMemberInnerToJSONTyped(value?: PostAdminFhirGroupsRequestMemberInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity': PostAdminFhirGroupsRequestMemberInnerEntityToJSON(value['entity']),
        'period': PostAdminFhirGroupsRequestMemberInnerPeriodToJSON(value['period']),
        'inactive': value['inactive'],
    };
}

