/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAuthLoginRequest
 */
export interface PostAuthLoginRequest {
    /**
     * Username or email
     * @type {string}
     * @memberof PostAuthLoginRequest
     */
    username: string;
    /**
     * Password
     * @type {string}
     * @memberof PostAuthLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the PostAuthLoginRequest interface.
 */
export function instanceOfPostAuthLoginRequest(value: object): value is PostAuthLoginRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PostAuthLoginRequestFromJSON(json: any): PostAuthLoginRequest {
    return PostAuthLoginRequestFromJSONTyped(json, false);
}

export function PostAuthLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function PostAuthLoginRequestToJSON(json: any): PostAuthLoginRequest {
    return PostAuthLoginRequestToJSONTyped(json, false);
}

export function PostAuthLoginRequestToJSONTyped(value?: PostAuthLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

