/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteAdminSmartAppsByClientId200Response
 */
export interface DeleteAdminSmartAppsByClientId200Response {
    /**
     * Whether the delete was successful
     * @type {boolean}
     * @memberof DeleteAdminSmartAppsByClientId200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteAdminSmartAppsByClientId200Response interface.
 */
export function instanceOfDeleteAdminSmartAppsByClientId200Response(value: object): value is DeleteAdminSmartAppsByClientId200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DeleteAdminSmartAppsByClientId200ResponseFromJSON(json: any): DeleteAdminSmartAppsByClientId200Response {
    return DeleteAdminSmartAppsByClientId200ResponseFromJSONTyped(json, false);
}

export function DeleteAdminSmartAppsByClientId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAdminSmartAppsByClientId200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function DeleteAdminSmartAppsByClientId200ResponseToJSON(json: any): DeleteAdminSmartAppsByClientId200Response {
    return DeleteAdminSmartAppsByClientId200ResponseToJSONTyped(json, false);
}

export function DeleteAdminSmartAppsByClientId200ResponseToJSONTyped(value?: DeleteAdminSmartAppsByClientId200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

