/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.4-RELEASE.202508041303.fa7ecc7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAuthIdps200ResponseInner
 */
export interface GetAuthIdps200ResponseInner {
    /**
     * Identity provider alias
     * @type {string}
     * @memberof GetAuthIdps200ResponseInner
     */
    alias: string;
    /**
     * Display name
     * @type {string}
     * @memberof GetAuthIdps200ResponseInner
     */
    displayName: string;
    /**
     * Provider type (oidc, saml, etc.)
     * @type {string}
     * @memberof GetAuthIdps200ResponseInner
     */
    providerId: string;
    /**
     * Whether the provider is enabled
     * @type {boolean}
     * @memberof GetAuthIdps200ResponseInner
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the GetAuthIdps200ResponseInner interface.
 */
export function instanceOfGetAuthIdps200ResponseInner(value: object): value is GetAuthIdps200ResponseInner {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    return true;
}

export function GetAuthIdps200ResponseInnerFromJSON(json: any): GetAuthIdps200ResponseInner {
    return GetAuthIdps200ResponseInnerFromJSONTyped(json, false);
}

export function GetAuthIdps200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAuthIdps200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'displayName': json['displayName'],
        'providerId': json['providerId'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function GetAuthIdps200ResponseInnerToJSON(json: any): GetAuthIdps200ResponseInner {
    return GetAuthIdps200ResponseInnerToJSONTyped(json, false);
}

export function GetAuthIdps200ResponseInnerToJSONTyped(value?: GetAuthIdps200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'displayName': value['displayName'],
        'providerId': value['providerId'],
        'enabled': value['enabled'],
    };
}

