/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdminLaunchContexts200ResponseInner
 */
export interface GetAdminLaunchContexts200ResponseInner {
    /**
     * User ID
     * @type {string}
     * @memberof GetAdminLaunchContexts200ResponseInner
     */
    userId: string;
    /**
     * Username
     * @type {string}
     * @memberof GetAdminLaunchContexts200ResponseInner
     */
    username: string;
    /**
     * Patient context
     * @type {string}
     * @memberof GetAdminLaunchContexts200ResponseInner
     */
    launchPatient: string;
    /**
     * Encounter context
     * @type {string}
     * @memberof GetAdminLaunchContexts200ResponseInner
     */
    launchEncounter: string;
}

/**
 * Check if a given object implements the GetAdminLaunchContexts200ResponseInner interface.
 */
export function instanceOfGetAdminLaunchContexts200ResponseInner(value: object): value is GetAdminLaunchContexts200ResponseInner {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('launchPatient' in value) || value['launchPatient'] === undefined) return false;
    if (!('launchEncounter' in value) || value['launchEncounter'] === undefined) return false;
    return true;
}

export function GetAdminLaunchContexts200ResponseInnerFromJSON(json: any): GetAdminLaunchContexts200ResponseInner {
    return GetAdminLaunchContexts200ResponseInnerFromJSONTyped(json, false);
}

export function GetAdminLaunchContexts200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminLaunchContexts200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'username': json['username'],
        'launchPatient': json['launchPatient'],
        'launchEncounter': json['launchEncounter'],
    };
}

export function GetAdminLaunchContexts200ResponseInnerToJSON(json: any): GetAdminLaunchContexts200ResponseInner {
    return GetAdminLaunchContexts200ResponseInnerToJSONTyped(json, false);
}

export function GetAdminLaunchContexts200ResponseInnerToJSONTyped(value?: GetAdminLaunchContexts200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'launchPatient': value['launchPatient'],
        'launchEncounter': value['launchEncounter'],
    };
}

