/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Maximum number of items to return
 * @export
 * @interface GetAdminHealthcareUsersLimitParameterAnyOf
 */
export interface GetAdminHealthcareUsersLimitParameterAnyOf {
}

/**
 * Check if a given object implements the GetAdminHealthcareUsersLimitParameterAnyOf interface.
 */
export function instanceOfGetAdminHealthcareUsersLimitParameterAnyOf(value: object): value is GetAdminHealthcareUsersLimitParameterAnyOf {
    return true;
}

export function GetAdminHealthcareUsersLimitParameterAnyOfFromJSON(json: any): GetAdminHealthcareUsersLimitParameterAnyOf {
    return GetAdminHealthcareUsersLimitParameterAnyOfFromJSONTyped(json, false);
}

export function GetAdminHealthcareUsersLimitParameterAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminHealthcareUsersLimitParameterAnyOf {
    return json;
}

export function GetAdminHealthcareUsersLimitParameterAnyOfToJSON(json: any): GetAdminHealthcareUsersLimitParameterAnyOf {
    return GetAdminHealthcareUsersLimitParameterAnyOfToJSONTyped(json, false);
}

export function GetAdminHealthcareUsersLimitParameterAnyOfToJSONTyped(value?: GetAdminHealthcareUsersLimitParameterAnyOf | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

