/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Number of items to skip
 * @export
 * @interface GetAdminHealthcareUsersOffsetParameterAnyOf
 */
export interface GetAdminHealthcareUsersOffsetParameterAnyOf {
}

/**
 * Check if a given object implements the GetAdminHealthcareUsersOffsetParameterAnyOf interface.
 */
export function instanceOfGetAdminHealthcareUsersOffsetParameterAnyOf(value: object): value is GetAdminHealthcareUsersOffsetParameterAnyOf {
    return true;
}

export function GetAdminHealthcareUsersOffsetParameterAnyOfFromJSON(json: any): GetAdminHealthcareUsersOffsetParameterAnyOf {
    return GetAdminHealthcareUsersOffsetParameterAnyOfFromJSONTyped(json, false);
}

export function GetAdminHealthcareUsersOffsetParameterAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminHealthcareUsersOffsetParameterAnyOf {
    return json;
}

export function GetAdminHealthcareUsersOffsetParameterAnyOfToJSON(json: any): GetAdminHealthcareUsersOffsetParameterAnyOf {
    return GetAdminHealthcareUsersOffsetParameterAnyOfToJSONTyped(json, false);
}

export function GetAdminHealthcareUsersOffsetParameterAnyOfToJSONTyped(value?: GetAdminHealthcareUsersOffsetParameterAnyOf | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

