/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdminRoles200ResponseInner
 */
export interface GetAdminRoles200ResponseInner {
    /**
     * Role ID
     * @type {string}
     * @memberof GetAdminRoles200ResponseInner
     */
    id?: string;
    /**
     * Role name
     * @type {string}
     * @memberof GetAdminRoles200ResponseInner
     */
    name?: string;
    /**
     * Role description
     * @type {string}
     * @memberof GetAdminRoles200ResponseInner
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof GetAdminRoles200ResponseInner
     */
    attributes?: object;
}

/**
 * Check if a given object implements the GetAdminRoles200ResponseInner interface.
 */
export function instanceOfGetAdminRoles200ResponseInner(value: object): value is GetAdminRoles200ResponseInner {
    return true;
}

export function GetAdminRoles200ResponseInnerFromJSON(json: any): GetAdminRoles200ResponseInner {
    return GetAdminRoles200ResponseInnerFromJSONTyped(json, false);
}

export function GetAdminRoles200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminRoles200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
    };
}

export function GetAdminRoles200ResponseInnerToJSON(json: any): GetAdminRoles200ResponseInner {
    return GetAdminRoles200ResponseInnerToJSONTyped(json, false);
}

export function GetAdminRoles200ResponseInnerToJSONTyped(value?: GetAdminRoles200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'attributes': value['attributes'],
    };
}

