/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAdminFhirGroups200ResponseInnerType } from './GetAdminFhirGroups200ResponseInnerType';
import {
    GetAdminFhirGroups200ResponseInnerTypeFromJSON,
    GetAdminFhirGroups200ResponseInnerTypeFromJSONTyped,
    GetAdminFhirGroups200ResponseInnerTypeToJSON,
    GetAdminFhirGroups200ResponseInnerTypeToJSONTyped,
} from './GetAdminFhirGroups200ResponseInnerType';

/**
 * 
 * @export
 * @interface GetAdminFhirGroups200ResponseInner
 */
export interface GetAdminFhirGroups200ResponseInner {
    /**
     * Group ID
     * @type {string}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    id: string;
    /**
     * Group name
     * @type {string}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {GetAdminFhirGroups200ResponseInnerType}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    type: GetAdminFhirGroups200ResponseInnerType;
    /**
     * Whether the group is active
     * @type {boolean}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    active: boolean;
    /**
     * Whether the group is actual or definitional
     * @type {boolean}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    actual: boolean;
    /**
     * Number of members in the group
     * @type {number}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    memberCount: number;
    /**
     * Description of the group
     * @type {string}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    description?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof GetAdminFhirGroups200ResponseInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the GetAdminFhirGroups200ResponseInner interface.
 */
export function instanceOfGetAdminFhirGroups200ResponseInner(value: object): value is GetAdminFhirGroups200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('actual' in value) || value['actual'] === undefined) return false;
    if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function GetAdminFhirGroups200ResponseInnerFromJSON(json: any): GetAdminFhirGroups200ResponseInner {
    return GetAdminFhirGroups200ResponseInnerFromJSONTyped(json, false);
}

export function GetAdminFhirGroups200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminFhirGroups200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': GetAdminFhirGroups200ResponseInnerTypeFromJSON(json['type']),
        'active': json['active'],
        'actual': json['actual'],
        'memberCount': json['memberCount'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function GetAdminFhirGroups200ResponseInnerToJSON(json: any): GetAdminFhirGroups200ResponseInner {
    return GetAdminFhirGroups200ResponseInnerToJSONTyped(json, false);
}

export function GetAdminFhirGroups200ResponseInnerToJSONTyped(value?: GetAdminFhirGroups200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': GetAdminFhirGroups200ResponseInnerTypeToJSON(value['type']),
        'active': value['active'],
        'actual': value['actual'],
        'memberCount': value['memberCount'],
        'description': value['description'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

