/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAdminHealthcareUsersOffsetParameterAnyOf } from './GetAdminHealthcareUsersOffsetParameterAnyOf';
import {
    GetAdminHealthcareUsersOffsetParameterAnyOfFromJSON,
    GetAdminHealthcareUsersOffsetParameterAnyOfFromJSONTyped,
    GetAdminHealthcareUsersOffsetParameterAnyOfToJSON,
    GetAdminHealthcareUsersOffsetParameterAnyOfToJSONTyped,
} from './GetAdminHealthcareUsersOffsetParameterAnyOf';

/**
 * 
 * @export
 * @interface GetAdminHealthcareUsersOffsetParameter
 */
export interface GetAdminHealthcareUsersOffsetParameter {
}

/**
 * Check if a given object implements the GetAdminHealthcareUsersOffsetParameter interface.
 */
export function instanceOfGetAdminHealthcareUsersOffsetParameter(value: object): value is GetAdminHealthcareUsersOffsetParameter {
    return true;
}

export function GetAdminHealthcareUsersOffsetParameterFromJSON(json: any): GetAdminHealthcareUsersOffsetParameter {
    return GetAdminHealthcareUsersOffsetParameterFromJSONTyped(json, false);
}

export function GetAdminHealthcareUsersOffsetParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdminHealthcareUsersOffsetParameter {
    return json;
}

export function GetAdminHealthcareUsersOffsetParameterToJSON(json: any): GetAdminHealthcareUsersOffsetParameter {
    return GetAdminHealthcareUsersOffsetParameterToJSONTyped(json, false);
}

export function GetAdminHealthcareUsersOffsetParameterToJSONTyped(value?: GetAdminHealthcareUsersOffsetParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

