/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetFhirServers200ResponseServersInnerEndpoints } from './GetFhirServers200ResponseServersInnerEndpoints';
import {
    GetFhirServers200ResponseServersInnerEndpointsFromJSON,
    GetFhirServers200ResponseServersInnerEndpointsFromJSONTyped,
    GetFhirServers200ResponseServersInnerEndpointsToJSON,
    GetFhirServers200ResponseServersInnerEndpointsToJSONTyped,
} from './GetFhirServers200ResponseServersInnerEndpoints';

/**
 * 
 * @export
 * @interface GetFhirServers200ResponseServersInner
 */
export interface GetFhirServers200ResponseServersInner {
    /**
     * Unique server identifier
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    id: string;
    /**
     * Human-readable server name
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    name: string;
    /**
     * Original server URL
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    url: string;
    /**
     * FHIR version supported by server
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    fhirVersion: string;
    /**
     * Server software version
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    serverVersion?: string;
    /**
     * Server software name from FHIR metadata
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    serverName?: string;
    /**
     * Whether this server is supported
     * @type {boolean}
     * @memberof GetFhirServers200ResponseServersInner
     */
    supported: boolean;
    /**
     * Error message if server info failed to fetch
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInner
     */
    error?: string;
    /**
     * 
     * @type {GetFhirServers200ResponseServersInnerEndpoints}
     * @memberof GetFhirServers200ResponseServersInner
     */
    endpoints: GetFhirServers200ResponseServersInnerEndpoints;
}

/**
 * Check if a given object implements the GetFhirServers200ResponseServersInner interface.
 */
export function instanceOfGetFhirServers200ResponseServersInner(value: object): value is GetFhirServers200ResponseServersInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('fhirVersion' in value) || value['fhirVersion'] === undefined) return false;
    if (!('supported' in value) || value['supported'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    return true;
}

export function GetFhirServers200ResponseServersInnerFromJSON(json: any): GetFhirServers200ResponseServersInner {
    return GetFhirServers200ResponseServersInnerFromJSONTyped(json, false);
}

export function GetFhirServers200ResponseServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFhirServers200ResponseServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'fhirVersion': json['fhirVersion'],
        'serverVersion': json['serverVersion'] == null ? undefined : json['serverVersion'],
        'serverName': json['serverName'] == null ? undefined : json['serverName'],
        'supported': json['supported'],
        'error': json['error'] == null ? undefined : json['error'],
        'endpoints': GetFhirServers200ResponseServersInnerEndpointsFromJSON(json['endpoints']),
    };
}

export function GetFhirServers200ResponseServersInnerToJSON(json: any): GetFhirServers200ResponseServersInner {
    return GetFhirServers200ResponseServersInnerToJSONTyped(json, false);
}

export function GetFhirServers200ResponseServersInnerToJSONTyped(value?: GetFhirServers200ResponseServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
        'fhirVersion': value['fhirVersion'],
        'serverVersion': value['serverVersion'],
        'serverName': value['serverName'],
        'supported': value['supported'],
        'error': value['error'],
        'endpoints': GetFhirServers200ResponseServersInnerEndpointsToJSON(value['endpoints']),
    };
}

