/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFhirServers200ResponseServersInnerEndpoints
 */
export interface GetFhirServers200ResponseServersInnerEndpoints {
    /**
     * Base FHIR endpoint URL
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInnerEndpoints
     */
    base: string;
    /**
     * SMART configuration endpoint URL
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInnerEndpoints
     */
    smartConfig: string;
    /**
     * FHIR metadata endpoint URL
     * @type {string}
     * @memberof GetFhirServers200ResponseServersInnerEndpoints
     */
    metadata: string;
}

/**
 * Check if a given object implements the GetFhirServers200ResponseServersInnerEndpoints interface.
 */
export function instanceOfGetFhirServers200ResponseServersInnerEndpoints(value: object): value is GetFhirServers200ResponseServersInnerEndpoints {
    if (!('base' in value) || value['base'] === undefined) return false;
    if (!('smartConfig' in value) || value['smartConfig'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function GetFhirServers200ResponseServersInnerEndpointsFromJSON(json: any): GetFhirServers200ResponseServersInnerEndpoints {
    return GetFhirServers200ResponseServersInnerEndpointsFromJSONTyped(json, false);
}

export function GetFhirServers200ResponseServersInnerEndpointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFhirServers200ResponseServersInnerEndpoints {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'],
        'smartConfig': json['smartConfig'],
        'metadata': json['metadata'],
    };
}

export function GetFhirServers200ResponseServersInnerEndpointsToJSON(json: any): GetFhirServers200ResponseServersInnerEndpoints {
    return GetFhirServers200ResponseServersInnerEndpointsToJSONTyped(json, false);
}

export function GetFhirServers200ResponseServersInnerEndpointsToJSONTyped(value?: GetFhirServers200ResponseServersInnerEndpoints | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'smartConfig': value['smartConfig'],
        'metadata': value['metadata'],
    };
}

