/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetFhirServersByServerIdMtls200ResponseCertDetails
 */
export interface GetFhirServersByServerIdMtls200ResponseCertDetails {
    /**
     * Certificate subject
     * @type {string}
     * @memberof GetFhirServersByServerIdMtls200ResponseCertDetails
     */
    subject: string;
    /**
     * Certificate issuer
     * @type {string}
     * @memberof GetFhirServersByServerIdMtls200ResponseCertDetails
     */
    issuer: string;
    /**
     * Certificate valid from date
     * @type {string}
     * @memberof GetFhirServersByServerIdMtls200ResponseCertDetails
     */
    validFrom: string;
    /**
     * Certificate valid to date
     * @type {string}
     * @memberof GetFhirServersByServerIdMtls200ResponseCertDetails
     */
    validTo: string;
    /**
     * Certificate fingerprint
     * @type {string}
     * @memberof GetFhirServersByServerIdMtls200ResponseCertDetails
     */
    fingerprint: string;
}

/**
 * Check if a given object implements the GetFhirServersByServerIdMtls200ResponseCertDetails interface.
 */
export function instanceOfGetFhirServersByServerIdMtls200ResponseCertDetails(value: object): value is GetFhirServersByServerIdMtls200ResponseCertDetails {
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('issuer' in value) || value['issuer'] === undefined) return false;
    if (!('validFrom' in value) || value['validFrom'] === undefined) return false;
    if (!('validTo' in value) || value['validTo'] === undefined) return false;
    if (!('fingerprint' in value) || value['fingerprint'] === undefined) return false;
    return true;
}

export function GetFhirServersByServerIdMtls200ResponseCertDetailsFromJSON(json: any): GetFhirServersByServerIdMtls200ResponseCertDetails {
    return GetFhirServersByServerIdMtls200ResponseCertDetailsFromJSONTyped(json, false);
}

export function GetFhirServersByServerIdMtls200ResponseCertDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFhirServersByServerIdMtls200ResponseCertDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'subject': json['subject'],
        'issuer': json['issuer'],
        'validFrom': json['validFrom'],
        'validTo': json['validTo'],
        'fingerprint': json['fingerprint'],
    };
}

export function GetFhirServersByServerIdMtls200ResponseCertDetailsToJSON(json: any): GetFhirServersByServerIdMtls200ResponseCertDetails {
    return GetFhirServersByServerIdMtls200ResponseCertDetailsToJSONTyped(json, false);
}

export function GetFhirServersByServerIdMtls200ResponseCertDetailsToJSONTyped(value?: GetFhirServersByServerIdMtls200ResponseCertDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subject': value['subject'],
        'issuer': value['issuer'],
        'validFrom': value['validFrom'],
        'validTo': value['validTo'],
        'fingerprint': value['fingerprint'],
    };
}

