/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508080014.2fe36ae
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealth200ResponseMemory
 */
export interface GetHealth200ResponseMemory {
    /**
     * Used memory in MB
     * @type {number}
     * @memberof GetHealth200ResponseMemory
     */
    used: number;
    /**
     * Total memory in MB
     * @type {number}
     * @memberof GetHealth200ResponseMemory
     */
    total: number;
}

/**
 * Check if a given object implements the GetHealth200ResponseMemory interface.
 */
export function instanceOfGetHealth200ResponseMemory(value: object): value is GetHealth200ResponseMemory {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function GetHealth200ResponseMemoryFromJSON(json: any): GetHealth200ResponseMemory {
    return GetHealth200ResponseMemoryFromJSONTyped(json, false);
}

export function GetHealth200ResponseMemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth200ResponseMemory {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'total': json['total'],
    };
}

export function GetHealth200ResponseMemoryToJSON(json: any): GetHealth200ResponseMemory {
    return GetHealth200ResponseMemoryToJSONTyped(json, false);
}

export function GetHealth200ResponseMemoryToJSONTyped(value?: GetHealth200ResponseMemory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'total': value['total'],
    };
}

