/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508080014.2fe36ae
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealth200ResponseFhirServersServersInner
 */
export interface GetHealth200ResponseFhirServersServersInner {
    /**
     * Server name
     * @type {string}
     * @memberof GetHealth200ResponseFhirServersServersInner
     */
    name: string;
    /**
     * Server status
     * @type {string}
     * @memberof GetHealth200ResponseFhirServersServersInner
     */
    status: string;
    /**
     * FHIR version
     * @type {string}
     * @memberof GetHealth200ResponseFhirServersServersInner
     */
    version: string;
}

/**
 * Check if a given object implements the GetHealth200ResponseFhirServersServersInner interface.
 */
export function instanceOfGetHealth200ResponseFhirServersServersInner(value: object): value is GetHealth200ResponseFhirServersServersInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function GetHealth200ResponseFhirServersServersInnerFromJSON(json: any): GetHealth200ResponseFhirServersServersInner {
    return GetHealth200ResponseFhirServersServersInnerFromJSONTyped(json, false);
}

export function GetHealth200ResponseFhirServersServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth200ResponseFhirServersServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'status': json['status'],
        'version': json['version'],
    };
}

export function GetHealth200ResponseFhirServersServersInnerToJSON(json: any): GetHealth200ResponseFhirServersServersInner {
    return GetHealth200ResponseFhirServersServersInnerToJSONTyped(json, false);
}

export function GetHealth200ResponseFhirServersServersInnerToJSONTyped(value?: GetHealth200ResponseFhirServersServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'status': value['status'],
        'version': value['version'],
    };
}

