/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMonitoringOauthEvents200ResponseEventsInnerFhirContext
 */
export interface GetMonitoringOauthEvents200ResponseEventsInnerFhirContext {
    /**
     * 
     * @type {string}
     * @memberof GetMonitoringOauthEvents200ResponseEventsInnerFhirContext
     */
    patient?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMonitoringOauthEvents200ResponseEventsInnerFhirContext
     */
    encounter?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMonitoringOauthEvents200ResponseEventsInnerFhirContext
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof GetMonitoringOauthEvents200ResponseEventsInnerFhirContext
     */
    fhirUser?: string;
}

/**
 * Check if a given object implements the GetMonitoringOauthEvents200ResponseEventsInnerFhirContext interface.
 */
export function instanceOfGetMonitoringOauthEvents200ResponseEventsInnerFhirContext(value: object): value is GetMonitoringOauthEvents200ResponseEventsInnerFhirContext {
    return true;
}

export function GetMonitoringOauthEvents200ResponseEventsInnerFhirContextFromJSON(json: any): GetMonitoringOauthEvents200ResponseEventsInnerFhirContext {
    return GetMonitoringOauthEvents200ResponseEventsInnerFhirContextFromJSONTyped(json, false);
}

export function GetMonitoringOauthEvents200ResponseEventsInnerFhirContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMonitoringOauthEvents200ResponseEventsInnerFhirContext {
    if (json == null) {
        return json;
    }
    return {
        
        'patient': json['patient'] == null ? undefined : json['patient'],
        'encounter': json['encounter'] == null ? undefined : json['encounter'],
        'location': json['location'] == null ? undefined : json['location'],
        'fhirUser': json['fhirUser'] == null ? undefined : json['fhirUser'],
    };
}

export function GetMonitoringOauthEvents200ResponseEventsInnerFhirContextToJSON(json: any): GetMonitoringOauthEvents200ResponseEventsInnerFhirContext {
    return GetMonitoringOauthEvents200ResponseEventsInnerFhirContextToJSONTyped(json, false);
}

export function GetMonitoringOauthEvents200ResponseEventsInnerFhirContextToJSONTyped(value?: GetMonitoringOauthEvents200ResponseEventsInnerFhirContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patient': value['patient'],
        'encounter': value['encounter'],
        'location': value['location'],
        'fhirUser': value['fhirUser'],
    };
}

