/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatus200ResponseMemory
 */
export interface GetStatus200ResponseMemory {
    /**
     * 
     * @type {number}
     * @memberof GetStatus200ResponseMemory
     */
    used: number;
    /**
     * 
     * @type {number}
     * @memberof GetStatus200ResponseMemory
     */
    total: number;
}

/**
 * Check if a given object implements the GetStatus200ResponseMemory interface.
 */
export function instanceOfGetStatus200ResponseMemory(value: object): value is GetStatus200ResponseMemory {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function GetStatus200ResponseMemoryFromJSON(json: any): GetStatus200ResponseMemory {
    return GetStatus200ResponseMemoryFromJSONTyped(json, false);
}

export function GetStatus200ResponseMemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseMemory {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'total': json['total'],
    };
}

export function GetStatus200ResponseMemoryToJSON(json: any): GetStatus200ResponseMemory {
    return GetStatus200ResponseMemoryToJSONTyped(json, false);
}

export function GetStatus200ResponseMemoryToJSONTyped(value?: GetStatus200ResponseMemory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'total': value['total'],
    };
}

