/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508080014.2fe36ae
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatus200ResponseServer
 */
export interface GetStatus200ResponseServer {
    /**
     * Server status
     * @type {string}
     * @memberof GetStatus200ResponseServer
     */
    status: string;
    /**
     * Server version
     * @type {string}
     * @memberof GetStatus200ResponseServer
     */
    version: string;
}

/**
 * Check if a given object implements the GetStatus200ResponseServer interface.
 */
export function instanceOfGetStatus200ResponseServer(value: object): value is GetStatus200ResponseServer {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function GetStatus200ResponseServerFromJSON(json: any): GetStatus200ResponseServer {
    return GetStatus200ResponseServerFromJSONTyped(json, false);
}

export function GetStatus200ResponseServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseServer {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'version': json['version'],
    };
}

export function GetStatus200ResponseServerToJSON(json: any): GetStatus200ResponseServer {
    return GetStatus200ResponseServerToJSONTyped(json, false);
}

export function GetStatus200ResponseServerToJSONTyped(value?: GetStatus200ResponseServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'version': value['version'],
    };
}

