/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508072141.a321362
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStatus200ResponseFhir } from './GetStatus200ResponseFhir';
import {
    GetStatus200ResponseFhirFromJSON,
    GetStatus200ResponseFhirFromJSONTyped,
    GetStatus200ResponseFhirToJSON,
    GetStatus200ResponseFhirToJSONTyped,
} from './GetStatus200ResponseFhir';
import type { GetStatus200ResponseServer } from './GetStatus200ResponseServer';
import {
    GetStatus200ResponseServerFromJSON,
    GetStatus200ResponseServerFromJSONTyped,
    GetStatus200ResponseServerToJSON,
    GetStatus200ResponseServerToJSONTyped,
} from './GetStatus200ResponseServer';
import type { GetStatus200ResponseKeycloak } from './GetStatus200ResponseKeycloak';
import {
    GetStatus200ResponseKeycloakFromJSON,
    GetStatus200ResponseKeycloakFromJSONTyped,
    GetStatus200ResponseKeycloakToJSON,
    GetStatus200ResponseKeycloakToJSONTyped,
} from './GetStatus200ResponseKeycloak';

/**
 * 
 * @export
 * @interface GetStatus200Response
 */
export interface GetStatus200Response {
    /**
     * Current timestamp
     * @type {string}
     * @memberof GetStatus200Response
     */
    timestamp: string;
    /**
     * Server uptime in seconds
     * @type {number}
     * @memberof GetStatus200Response
     */
    uptime: number;
    /**
     * 
     * @type {GetStatus200ResponseServer}
     * @memberof GetStatus200Response
     */
    server: GetStatus200ResponseServer;
    /**
     * 
     * @type {GetStatus200ResponseFhir}
     * @memberof GetStatus200Response
     */
    fhir: GetStatus200ResponseFhir;
    /**
     * 
     * @type {GetStatus200ResponseKeycloak}
     * @memberof GetStatus200Response
     */
    keycloak: GetStatus200ResponseKeycloak;
}

/**
 * Check if a given object implements the GetStatus200Response interface.
 */
export function instanceOfGetStatus200Response(value: object): value is GetStatus200Response {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    if (!('server' in value) || value['server'] === undefined) return false;
    if (!('fhir' in value) || value['fhir'] === undefined) return false;
    if (!('keycloak' in value) || value['keycloak'] === undefined) return false;
    return true;
}

export function GetStatus200ResponseFromJSON(json: any): GetStatus200Response {
    return GetStatus200ResponseFromJSONTyped(json, false);
}

export function GetStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'uptime': json['uptime'],
        'server': GetStatus200ResponseServerFromJSON(json['server']),
        'fhir': GetStatus200ResponseFhirFromJSON(json['fhir']),
        'keycloak': GetStatus200ResponseKeycloakFromJSON(json['keycloak']),
    };
}

export function GetStatus200ResponseToJSON(json: any): GetStatus200Response {
    return GetStatus200ResponseToJSONTyped(json, false);
}

export function GetStatus200ResponseToJSONTyped(value?: GetStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'uptime': value['uptime'],
        'server': GetStatus200ResponseServerToJSON(value['server']),
        'fhir': GetStatus200ResponseFhirToJSON(value['fhir']),
        'keycloak': GetStatus200ResponseKeycloakToJSON(value['keycloak']),
    };
}

