/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.2-alpha.202508031904.f48c087
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatus200ResponseFhirServersInner
 */
export interface GetStatus200ResponseFhirServersInner {
    /**
     * Server name
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    name: string;
    /**
     * Server URL
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    url: string;
    /**
     * Server status
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    status: string;
    /**
     * Whether server is accessible
     * @type {boolean}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    accessible: boolean;
    /**
     * FHIR version
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    version: string;
    /**
     * FHIR server software name
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    serverName?: string;
    /**
     * FHIR server software version
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    serverVersion?: string;
    /**
     * Error message if unhealthy
     * @type {string}
     * @memberof GetStatus200ResponseFhirServersInner
     */
    error?: string;
}

/**
 * Check if a given object implements the GetStatus200ResponseFhirServersInner interface.
 */
export function instanceOfGetStatus200ResponseFhirServersInner(value: object): value is GetStatus200ResponseFhirServersInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('accessible' in value) || value['accessible'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function GetStatus200ResponseFhirServersInnerFromJSON(json: any): GetStatus200ResponseFhirServersInner {
    return GetStatus200ResponseFhirServersInnerFromJSONTyped(json, false);
}

export function GetStatus200ResponseFhirServersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseFhirServersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'status': json['status'],
        'accessible': json['accessible'],
        'version': json['version'],
        'serverName': json['serverName'] == null ? undefined : json['serverName'],
        'serverVersion': json['serverVersion'] == null ? undefined : json['serverVersion'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetStatus200ResponseFhirServersInnerToJSON(json: any): GetStatus200ResponseFhirServersInner {
    return GetStatus200ResponseFhirServersInnerToJSONTyped(json, false);
}

export function GetStatus200ResponseFhirServersInnerToJSONTyped(value?: GetStatus200ResponseFhirServersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'status': value['status'],
        'accessible': value['accessible'],
        'version': value['version'],
        'serverName': value['serverName'],
        'serverVersion': value['serverVersion'],
        'error': value['error'],
    };
}

