/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetStatus200ResponseFhirServersInner } from './GetStatus200ResponseFhirServersInner';
import {
    GetStatus200ResponseFhirServersInnerFromJSON,
    GetStatus200ResponseFhirServersInnerFromJSONTyped,
    GetStatus200ResponseFhirServersInnerToJSON,
    GetStatus200ResponseFhirServersInnerToJSONTyped,
} from './GetStatus200ResponseFhirServersInner';

/**
 * 
 * @export
 * @interface GetStatus200ResponseFhir
 */
export interface GetStatus200ResponseFhir {
    /**
     * 
     * @type {string}
     * @memberof GetStatus200ResponseFhir
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof GetStatus200ResponseFhir
     */
    totalServers: number;
    /**
     * 
     * @type {number}
     * @memberof GetStatus200ResponseFhir
     */
    healthyServers: number;
    /**
     * 
     * @type {Array<GetStatus200ResponseFhirServersInner>}
     * @memberof GetStatus200ResponseFhir
     */
    servers: Array<GetStatus200ResponseFhirServersInner>;
}

/**
 * Check if a given object implements the GetStatus200ResponseFhir interface.
 */
export function instanceOfGetStatus200ResponseFhir(value: object): value is GetStatus200ResponseFhir {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalServers' in value) || value['totalServers'] === undefined) return false;
    if (!('healthyServers' in value) || value['healthyServers'] === undefined) return false;
    if (!('servers' in value) || value['servers'] === undefined) return false;
    return true;
}

export function GetStatus200ResponseFhirFromJSON(json: any): GetStatus200ResponseFhir {
    return GetStatus200ResponseFhirFromJSONTyped(json, false);
}

export function GetStatus200ResponseFhirFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseFhir {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'totalServers': json['totalServers'],
        'healthyServers': json['healthyServers'],
        'servers': ((json['servers'] as Array<any>).map(GetStatus200ResponseFhirServersInnerFromJSON)),
    };
}

export function GetStatus200ResponseFhirToJSON(json: any): GetStatus200ResponseFhir {
    return GetStatus200ResponseFhirToJSONTyped(json, false);
}

export function GetStatus200ResponseFhirToJSONTyped(value?: GetStatus200ResponseFhir | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'totalServers': value['totalServers'],
        'healthyServers': value['healthyServers'],
        'servers': ((value['servers'] as Array<any>).map(GetStatus200ResponseFhirServersInnerToJSON)),
    };
}

