/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508080014.2fe36ae
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostShutdown500Response
 */
export interface PostShutdown500Response {
    /**
     * Error message
     * @type {string}
     * @memberof PostShutdown500Response
     */
    error: string;
    /**
     * Error code
     * @type {string}
     * @memberof PostShutdown500Response
     */
    code?: string;
    /**
     * Additional error details
     * @type {any}
     * @memberof PostShutdown500Response
     */
    details?: any | null;
}

/**
 * Check if a given object implements the PostShutdown500Response interface.
 */
export function instanceOfPostShutdown500Response(value: object): value is PostShutdown500Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function PostShutdown500ResponseFromJSON(json: any): PostShutdown500Response {
    return PostShutdown500ResponseFromJSONTyped(json, false);
}

export function PostShutdown500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostShutdown500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function PostShutdown500ResponseToJSON(json: any): PostShutdown500Response {
    return PostShutdown500ResponseToJSONTyped(json, false);
}

export function PostShutdown500ResponseToJSONTyped(value?: PostShutdown500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'code': value['code'],
        'details': value['details'],
    };
}

