/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAuthToken200Response
 */
export interface PostAuthToken200Response {
    /**
     * JWT access token
     * @type {string}
     * @memberof PostAuthToken200Response
     */
    accessToken?: string;
    /**
     * Token type (Bearer)
     * @type {string}
     * @memberof PostAuthToken200Response
     */
    tokenType?: string;
    /**
     * Token expiration time in seconds
     * @type {number}
     * @memberof PostAuthToken200Response
     */
    expiresIn?: number;
    /**
     * Refresh token
     * @type {string}
     * @memberof PostAuthToken200Response
     */
    refreshToken?: string;
    /**
     * Granted scopes
     * @type {string}
     * @memberof PostAuthToken200Response
     */
    scope?: string;
}

/**
 * Check if a given object implements the PostAuthToken200Response interface.
 */
export function instanceOfPostAuthToken200Response(value: object): value is PostAuthToken200Response {
    return true;
}

export function PostAuthToken200ResponseFromJSON(json: any): PostAuthToken200Response {
    return PostAuthToken200ResponseFromJSONTyped(json, false);
}

export function PostAuthToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function PostAuthToken200ResponseToJSON(json: any): PostAuthToken200Response {
    return PostAuthToken200ResponseToJSONTyped(json, false);
}

export function PostAuthToken200ResponseToJSONTyped(value?: PostAuthToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'scope': value['scope'],
    };
}

