/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInner } from './PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInner';
import {
    PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInnerFromJSON,
    PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInnerFromJSONTyped,
    PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInnerToJSON,
    PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInnerToJSONTyped,
} from './PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInner';

/**
 * 
 * @export
 * @interface PostAdminFhirGroupsRequestIdentifierInnerType
 */
export interface PostAdminFhirGroupsRequestIdentifierInnerType {
    /**
     * 
     * @type {Array<PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInner>}
     * @memberof PostAdminFhirGroupsRequestIdentifierInnerType
     */
    coding?: Array<PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInner>;
}

/**
 * Check if a given object implements the PostAdminFhirGroupsRequestIdentifierInnerType interface.
 */
export function instanceOfPostAdminFhirGroupsRequestIdentifierInnerType(value: object): value is PostAdminFhirGroupsRequestIdentifierInnerType {
    return true;
}

export function PostAdminFhirGroupsRequestIdentifierInnerTypeFromJSON(json: any): PostAdminFhirGroupsRequestIdentifierInnerType {
    return PostAdminFhirGroupsRequestIdentifierInnerTypeFromJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestIdentifierInnerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminFhirGroupsRequestIdentifierInnerType {
    if (json == null) {
        return json;
    }
    return {
        
        'coding': json['coding'] == null ? undefined : ((json['coding'] as Array<any>).map(PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInnerFromJSON)),
    };
}

export function PostAdminFhirGroupsRequestIdentifierInnerTypeToJSON(json: any): PostAdminFhirGroupsRequestIdentifierInnerType {
    return PostAdminFhirGroupsRequestIdentifierInnerTypeToJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestIdentifierInnerTypeToJSONTyped(value?: PostAdminFhirGroupsRequestIdentifierInnerType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coding': value['coding'] == null ? undefined : ((value['coding'] as Array<any>).map(PostAdminFhirGroupsRequestIdentifierInnerTypeCodingInnerToJSON)),
    };
}

