/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAdminFhirGroupsRequestMemberInnerPeriod
 */
export interface PostAdminFhirGroupsRequestMemberInnerPeriod {
    /**
     * Start time
     * @type {string}
     * @memberof PostAdminFhirGroupsRequestMemberInnerPeriod
     */
    start?: string;
    /**
     * End time
     * @type {string}
     * @memberof PostAdminFhirGroupsRequestMemberInnerPeriod
     */
    end?: string;
}

/**
 * Check if a given object implements the PostAdminFhirGroupsRequestMemberInnerPeriod interface.
 */
export function instanceOfPostAdminFhirGroupsRequestMemberInnerPeriod(value: object): value is PostAdminFhirGroupsRequestMemberInnerPeriod {
    return true;
}

export function PostAdminFhirGroupsRequestMemberInnerPeriodFromJSON(json: any): PostAdminFhirGroupsRequestMemberInnerPeriod {
    return PostAdminFhirGroupsRequestMemberInnerPeriodFromJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestMemberInnerPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminFhirGroupsRequestMemberInnerPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
    };
}

export function PostAdminFhirGroupsRequestMemberInnerPeriodToJSON(json: any): PostAdminFhirGroupsRequestMemberInnerPeriod {
    return PostAdminFhirGroupsRequestMemberInnerPeriodToJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestMemberInnerPeriodToJSONTyped(value?: PostAdminFhirGroupsRequestMemberInnerPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

