/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfo } from './PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfo';
import {
    PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfoFromJSON,
    PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfoFromJSONTyped,
    PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfoToJSON,
    PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfoToJSONTyped,
} from './PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfo';

/**
 * 
 * @export
 * @interface PostVByFhirReleaseFhirCacheRefresh200Response
 */
export interface PostVByFhirReleaseFhirCacheRefresh200Response {
    /**
     * Whether refresh was successful
     * @type {boolean}
     * @memberof PostVByFhirReleaseFhirCacheRefresh200Response
     */
    success: boolean;
    /**
     * Success message
     * @type {string}
     * @memberof PostVByFhirReleaseFhirCacheRefresh200Response
     */
    message: string;
    /**
     * 
     * @type {PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfo}
     * @memberof PostVByFhirReleaseFhirCacheRefresh200Response
     */
    serverInfo: PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfo;
}

/**
 * Check if a given object implements the PostVByFhirReleaseFhirCacheRefresh200Response interface.
 */
export function instanceOfPostVByFhirReleaseFhirCacheRefresh200Response(value: object): value is PostVByFhirReleaseFhirCacheRefresh200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('serverInfo' in value) || value['serverInfo'] === undefined) return false;
    return true;
}

export function PostVByFhirReleaseFhirCacheRefresh200ResponseFromJSON(json: any): PostVByFhirReleaseFhirCacheRefresh200Response {
    return PostVByFhirReleaseFhirCacheRefresh200ResponseFromJSONTyped(json, false);
}

export function PostVByFhirReleaseFhirCacheRefresh200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVByFhirReleaseFhirCacheRefresh200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'serverInfo': PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfoFromJSON(json['serverInfo']),
    };
}

export function PostVByFhirReleaseFhirCacheRefresh200ResponseToJSON(json: any): PostVByFhirReleaseFhirCacheRefresh200Response {
    return PostVByFhirReleaseFhirCacheRefresh200ResponseToJSONTyped(json, false);
}

export function PostVByFhirReleaseFhirCacheRefresh200ResponseToJSONTyped(value?: PostVByFhirReleaseFhirCacheRefresh200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'serverInfo': PostVByFhirReleaseFhirCacheRefresh200ResponseServerInfoToJSON(value['serverInfo']),
    };
}

