/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAdminShutdown200Response
 */
export interface PostAdminShutdown200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PostAdminShutdown200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostAdminShutdown200Response
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof PostAdminShutdown200Response
     */
    timestamp: string;
}

/**
 * Check if a given object implements the PostAdminShutdown200Response interface.
 */
export function instanceOfPostAdminShutdown200Response(value: object): value is PostAdminShutdown200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PostAdminShutdown200ResponseFromJSON(json: any): PostAdminShutdown200Response {
    return PostAdminShutdown200ResponseFromJSONTyped(json, false);
}

export function PostAdminShutdown200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminShutdown200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function PostAdminShutdown200ResponseToJSON(json: any): PostAdminShutdown200Response {
    return PostAdminShutdown200ResponseToJSONTyped(json, false);
}

export function PostAdminShutdown200ResponseToJSONTyped(value?: PostAdminShutdown200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

