/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508080014.2fe36ae
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostShutdown200Response
 */
export interface PostShutdown200Response {
    /**
     * Whether shutdown was initiated successfully
     * @type {boolean}
     * @memberof PostShutdown200Response
     */
    success: boolean;
    /**
     * Shutdown status message
     * @type {string}
     * @memberof PostShutdown200Response
     */
    message: string;
    /**
     * Timestamp when shutdown was initiated
     * @type {string}
     * @memberof PostShutdown200Response
     */
    timestamp: string;
}

/**
 * Check if a given object implements the PostShutdown200Response interface.
 */
export function instanceOfPostShutdown200Response(value: object): value is PostShutdown200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PostShutdown200ResponseFromJSON(json: any): PostShutdown200Response {
    return PostShutdown200ResponseFromJSONTyped(json, false);
}

export function PostShutdown200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostShutdown200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function PostShutdown200ResponseToJSON(json: any): PostShutdown200Response {
    return PostShutdown200ResponseToJSONTyped(json, false);
}

export function PostShutdown200ResponseToJSONTyped(value?: PostShutdown200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

