/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAdminFhirGroupsRequestMemberInnerEntity
 */
export interface PostAdminFhirGroupsRequestMemberInnerEntity {
    /**
     * Reference to the entity
     * @type {string}
     * @memberof PostAdminFhirGroupsRequestMemberInnerEntity
     */
    reference: string;
    /**
     * Display text for the entity
     * @type {string}
     * @memberof PostAdminFhirGroupsRequestMemberInnerEntity
     */
    display?: string;
}

/**
 * Check if a given object implements the PostAdminFhirGroupsRequestMemberInnerEntity interface.
 */
export function instanceOfPostAdminFhirGroupsRequestMemberInnerEntity(value: object): value is PostAdminFhirGroupsRequestMemberInnerEntity {
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function PostAdminFhirGroupsRequestMemberInnerEntityFromJSON(json: any): PostAdminFhirGroupsRequestMemberInnerEntity {
    return PostAdminFhirGroupsRequestMemberInnerEntityFromJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestMemberInnerEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminFhirGroupsRequestMemberInnerEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'],
        'display': json['display'] == null ? undefined : json['display'],
    };
}

export function PostAdminFhirGroupsRequestMemberInnerEntityToJSON(json: any): PostAdminFhirGroupsRequestMemberInnerEntity {
    return PostAdminFhirGroupsRequestMemberInnerEntityToJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestMemberInnerEntityToJSONTyped(value?: PostAdminFhirGroupsRequestMemberInnerEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'display': value['display'],
    };
}

