/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAdminFhirGroups200ResponseInnerType } from './GetAdminFhirGroups200ResponseInnerType';
import {
    GetAdminFhirGroups200ResponseInnerTypeFromJSON,
    GetAdminFhirGroups200ResponseInnerTypeFromJSONTyped,
    GetAdminFhirGroups200ResponseInnerTypeToJSON,
    GetAdminFhirGroups200ResponseInnerTypeToJSONTyped,
} from './GetAdminFhirGroups200ResponseInnerType';

/**
 * 
 * @export
 * @interface PostAdminFhirGroups200Response
 */
export interface PostAdminFhirGroups200Response {
    /**
     * Unique identifier for the group
     * @type {string}
     * @memberof PostAdminFhirGroups200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PostAdminFhirGroups200Response
     */
    resourceType: string;
    /**
     * Whether the group is active
     * @type {boolean}
     * @memberof PostAdminFhirGroups200Response
     */
    active: boolean;
    /**
     * 
     * @type {GetAdminFhirGroups200ResponseInnerType}
     * @memberof PostAdminFhirGroups200Response
     */
    type: GetAdminFhirGroups200ResponseInnerType;
    /**
     * Whether the group is actual (true) or definitional (false)
     * @type {boolean}
     * @memberof PostAdminFhirGroups200Response
     */
    actual: boolean;
    /**
     * Human-readable name for the group
     * @type {string}
     * @memberof PostAdminFhirGroups200Response
     */
    name: string;
    /**
     * Description of the group
     * @type {string}
     * @memberof PostAdminFhirGroups200Response
     */
    description?: string;
    /**
     * Number of members in the group
     * @type {number}
     * @memberof PostAdminFhirGroups200Response
     */
    memberCount?: number;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof PostAdminFhirGroups200Response
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof PostAdminFhirGroups200Response
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PostAdminFhirGroups200Response interface.
 */
export function instanceOfPostAdminFhirGroups200Response(value: object): value is PostAdminFhirGroups200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('actual' in value) || value['actual'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PostAdminFhirGroups200ResponseFromJSON(json: any): PostAdminFhirGroups200Response {
    return PostAdminFhirGroups200ResponseFromJSONTyped(json, false);
}

export function PostAdminFhirGroups200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminFhirGroups200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'resourceType': json['resourceType'],
        'active': json['active'],
        'type': GetAdminFhirGroups200ResponseInnerTypeFromJSON(json['type']),
        'actual': json['actual'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function PostAdminFhirGroups200ResponseToJSON(json: any): PostAdminFhirGroups200Response {
    return PostAdminFhirGroups200ResponseToJSONTyped(json, false);
}

export function PostAdminFhirGroups200ResponseToJSONTyped(value?: PostAdminFhirGroups200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'resourceType': value['resourceType'],
        'active': value['active'],
        'type': GetAdminFhirGroups200ResponseInnerTypeToJSON(value['type']),
        'actual': value['actual'],
        'name': value['name'],
        'description': value['description'],
        'memberCount': value['memberCount'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

