/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostFhirServers401Response
 */
export interface PostFhirServers401Response {
    /**
     * Error message
     * @type {string}
     * @memberof PostFhirServers401Response
     */
    error: string;
}

/**
 * Check if a given object implements the PostFhirServers401Response interface.
 */
export function instanceOfPostFhirServers401Response(value: object): value is PostFhirServers401Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function PostFhirServers401ResponseFromJSON(json: any): PostFhirServers401Response {
    return PostFhirServers401ResponseFromJSONTyped(json, false);
}

export function PostFhirServers401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostFhirServers401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function PostFhirServers401ResponseToJSON(json: any): PostFhirServers401Response {
    return PostFhirServers401ResponseToJSONTyped(json, false);
}

export function PostFhirServers401ResponseToJSONTyped(value?: PostFhirServers401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

