/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetFhirServersByServerIdMtls200ResponseCertDetails } from './GetFhirServersByServerIdMtls200ResponseCertDetails';
import {
    GetFhirServersByServerIdMtls200ResponseCertDetailsFromJSON,
    GetFhirServersByServerIdMtls200ResponseCertDetailsFromJSONTyped,
    GetFhirServersByServerIdMtls200ResponseCertDetailsToJSON,
    GetFhirServersByServerIdMtls200ResponseCertDetailsToJSONTyped,
} from './GetFhirServersByServerIdMtls200ResponseCertDetails';

/**
 * 
 * @export
 * @interface PostFhirServersByServerIdMtlsCertificates200Response
 */
export interface PostFhirServersByServerIdMtlsCertificates200Response {
    /**
     * Whether the upload was successful
     * @type {boolean}
     * @memberof PostFhirServersByServerIdMtlsCertificates200Response
     */
    success: boolean;
    /**
     * Success message
     * @type {string}
     * @memberof PostFhirServersByServerIdMtlsCertificates200Response
     */
    message: string;
    /**
     * 
     * @type {GetFhirServersByServerIdMtls200ResponseCertDetails}
     * @memberof PostFhirServersByServerIdMtlsCertificates200Response
     */
    certDetails?: GetFhirServersByServerIdMtls200ResponseCertDetails;
}

/**
 * Check if a given object implements the PostFhirServersByServerIdMtlsCertificates200Response interface.
 */
export function instanceOfPostFhirServersByServerIdMtlsCertificates200Response(value: object): value is PostFhirServersByServerIdMtlsCertificates200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PostFhirServersByServerIdMtlsCertificates200ResponseFromJSON(json: any): PostFhirServersByServerIdMtlsCertificates200Response {
    return PostFhirServersByServerIdMtlsCertificates200ResponseFromJSONTyped(json, false);
}

export function PostFhirServersByServerIdMtlsCertificates200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostFhirServersByServerIdMtlsCertificates200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'certDetails': json['certDetails'] == null ? undefined : GetFhirServersByServerIdMtls200ResponseCertDetailsFromJSON(json['certDetails']),
    };
}

export function PostFhirServersByServerIdMtlsCertificates200ResponseToJSON(json: any): PostFhirServersByServerIdMtlsCertificates200Response {
    return PostFhirServersByServerIdMtlsCertificates200ResponseToJSONTyped(json, false);
}

export function PostFhirServersByServerIdMtlsCertificates200ResponseToJSONTyped(value?: PostFhirServersByServerIdMtlsCertificates200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'certDetails': GetFhirServersByServerIdMtls200ResponseCertDetailsToJSON(value['certDetails']),
    };
}

