/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow
 */
export interface PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow {
    /**
     * 
     * @type {number}
     * @memberof PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow
     */
    unit?: string;
}

/**
 * Check if a given object implements the PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow interface.
 */
export function instanceOfPostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow(value: object): value is PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow {
    return true;
}

export function PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLowFromJSON(json: any): PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow {
    return PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLowFromJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLowFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLowToJSON(json: any): PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow {
    return PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLowToJSONTyped(json, false);
}

export function PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLowToJSONTyped(value?: PostAdminFhirGroupsRequestCharacteristicInnerValueRangeLow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'unit': value['unit'],
    };
}

