/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAuthToken200ResponseFhirContextInner
 */
export interface PostAuthToken200ResponseFhirContextInner {
    /**
     * FHIR resource reference
     * @type {string}
     * @memberof PostAuthToken200ResponseFhirContextInner
     */
    reference?: string;
    /**
     * Canonical URL
     * @type {string}
     * @memberof PostAuthToken200ResponseFhirContextInner
     */
    canonical?: string;
    /**
     * FHIR Identifier
     * @type {object}
     * @memberof PostAuthToken200ResponseFhirContextInner
     */
    identifier?: object;
    /**
     * FHIR resource type
     * @type {string}
     * @memberof PostAuthToken200ResponseFhirContextInner
     */
    type?: string;
    /**
     * Role URI
     * @type {string}
     * @memberof PostAuthToken200ResponseFhirContextInner
     */
    role?: string;
}

/**
 * Check if a given object implements the PostAuthToken200ResponseFhirContextInner interface.
 */
export function instanceOfPostAuthToken200ResponseFhirContextInner(value: object): value is PostAuthToken200ResponseFhirContextInner {
    return true;
}

export function PostAuthToken200ResponseFhirContextInnerFromJSON(json: any): PostAuthToken200ResponseFhirContextInner {
    return PostAuthToken200ResponseFhirContextInnerFromJSONTyped(json, false);
}

export function PostAuthToken200ResponseFhirContextInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAuthToken200ResponseFhirContextInner {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'] == null ? undefined : json['reference'],
        'canonical': json['canonical'] == null ? undefined : json['canonical'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'type': json['type'] == null ? undefined : json['type'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function PostAuthToken200ResponseFhirContextInnerToJSON(json: any): PostAuthToken200ResponseFhirContextInner {
    return PostAuthToken200ResponseFhirContextInnerToJSONTyped(json, false);
}

export function PostAuthToken200ResponseFhirContextInnerToJSONTyped(value?: PostAuthToken200ResponseFhirContextInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'canonical': value['canonical'],
        'identifier': value['identifier'],
        'type': value['type'],
        'role': value['role'],
    };
}

