/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostRestart500Response
 */
export interface PostRestart500Response {
    /**
     * Error message
     * @type {string}
     * @memberof PostRestart500Response
     */
    error: string;
    /**
     * Error code
     * @type {string}
     * @memberof PostRestart500Response
     */
    code?: string;
    /**
     * Additional error details
     * @type {any}
     * @memberof PostRestart500Response
     */
    details?: any | null;
}

/**
 * Check if a given object implements the PostRestart500Response interface.
 */
export function instanceOfPostRestart500Response(value: object): value is PostRestart500Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function PostRestart500ResponseFromJSON(json: any): PostRestart500Response {
    return PostRestart500ResponseFromJSONTyped(json, false);
}

export function PostRestart500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRestart500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'code': json['code'] == null ? undefined : json['code'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function PostRestart500ResponseToJSON(json: any): PostRestart500Response {
    return PostRestart500ResponseToJSONTyped(json, false);
}

export function PostRestart500ResponseToJSONTyped(value?: PostRestart500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'code': value['code'],
        'details': value['details'],
    };
}

