/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutAdminSmartAppsByClientIdRequest
 */
export interface PutAdminSmartAppsByClientIdRequest {
    /**
     * Application name
     * @type {string}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    name?: string;
    /**
     * Application description
     * @type {string}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    description?: string;
    /**
     * Whether application is enabled
     * @type {boolean}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    redirectUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    webOrigins?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    defaultScopes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    optionalScopes?: Array<string>;
    /**
     * SMART version
     * @type {string}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    smartVersion?: string;
    /**
     * FHIR version
     * @type {string}
     * @memberof PutAdminSmartAppsByClientIdRequest
     */
    fhirVersion?: string;
}

/**
 * Check if a given object implements the PutAdminSmartAppsByClientIdRequest interface.
 */
export function instanceOfPutAdminSmartAppsByClientIdRequest(value: object): value is PutAdminSmartAppsByClientIdRequest {
    return true;
}

export function PutAdminSmartAppsByClientIdRequestFromJSON(json: any): PutAdminSmartAppsByClientIdRequest {
    return PutAdminSmartAppsByClientIdRequestFromJSONTyped(json, false);
}

export function PutAdminSmartAppsByClientIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminSmartAppsByClientIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'redirectUris': json['redirectUris'] == null ? undefined : json['redirectUris'],
        'webOrigins': json['webOrigins'] == null ? undefined : json['webOrigins'],
        'defaultScopes': json['defaultScopes'] == null ? undefined : json['defaultScopes'],
        'optionalScopes': json['optionalScopes'] == null ? undefined : json['optionalScopes'],
        'smartVersion': json['smartVersion'] == null ? undefined : json['smartVersion'],
        'fhirVersion': json['fhirVersion'] == null ? undefined : json['fhirVersion'],
    };
}

export function PutAdminSmartAppsByClientIdRequestToJSON(json: any): PutAdminSmartAppsByClientIdRequest {
    return PutAdminSmartAppsByClientIdRequestToJSONTyped(json, false);
}

export function PutAdminSmartAppsByClientIdRequestToJSONTyped(value?: PutAdminSmartAppsByClientIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'enabled': value['enabled'],
        'redirectUris': value['redirectUris'],
        'webOrigins': value['webOrigins'],
        'defaultScopes': value['defaultScopes'],
        'optionalScopes': value['optionalScopes'],
        'smartVersion': value['smartVersion'],
        'fhirVersion': value['fhirVersion'],
    };
}

