/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutAdminIdpsByAliasRequestConfig
 */
export interface PutAdminIdpsByAliasRequestConfig {
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    singleSignOnServiceUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    singleLogoutServiceUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    metadataDescriptorUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    clientSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    tokenUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    userInfoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    issuer?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    defaultScopes?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    logoutUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    signatureAlgorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    nameIdPolicyFormat?: string;
    /**
     * 
     * @type {string}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    signingCertificate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    validateSignature?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    wantAuthnRequestsSigned?: boolean;
    /**
     * 
     * @type {object}
     * @memberof PutAdminIdpsByAliasRequestConfig
     */
    additionalConfig?: object;
}

/**
 * Check if a given object implements the PutAdminIdpsByAliasRequestConfig interface.
 */
export function instanceOfPutAdminIdpsByAliasRequestConfig(value: object): value is PutAdminIdpsByAliasRequestConfig {
    return true;
}

export function PutAdminIdpsByAliasRequestConfigFromJSON(json: any): PutAdminIdpsByAliasRequestConfig {
    return PutAdminIdpsByAliasRequestConfigFromJSONTyped(json, false);
}

export function PutAdminIdpsByAliasRequestConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminIdpsByAliasRequestConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
        'singleSignOnServiceUrl': json['singleSignOnServiceUrl'] == null ? undefined : json['singleSignOnServiceUrl'],
        'singleLogoutServiceUrl': json['singleLogoutServiceUrl'] == null ? undefined : json['singleLogoutServiceUrl'],
        'metadataDescriptorUrl': json['metadataDescriptorUrl'] == null ? undefined : json['metadataDescriptorUrl'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'clientSecret': json['clientSecret'] == null ? undefined : json['clientSecret'],
        'tokenUrl': json['tokenUrl'] == null ? undefined : json['tokenUrl'],
        'userInfoUrl': json['userInfoUrl'] == null ? undefined : json['userInfoUrl'],
        'issuer': json['issuer'] == null ? undefined : json['issuer'],
        'defaultScopes': json['defaultScopes'] == null ? undefined : json['defaultScopes'],
        'logoutUrl': json['logoutUrl'] == null ? undefined : json['logoutUrl'],
        'signatureAlgorithm': json['signatureAlgorithm'] == null ? undefined : json['signatureAlgorithm'],
        'nameIdPolicyFormat': json['nameIdPolicyFormat'] == null ? undefined : json['nameIdPolicyFormat'],
        'signingCertificate': json['signingCertificate'] == null ? undefined : json['signingCertificate'],
        'validateSignature': json['validateSignature'] == null ? undefined : json['validateSignature'],
        'wantAuthnRequestsSigned': json['wantAuthnRequestsSigned'] == null ? undefined : json['wantAuthnRequestsSigned'],
        'additionalConfig': json['additionalConfig'] == null ? undefined : json['additionalConfig'],
    };
}

export function PutAdminIdpsByAliasRequestConfigToJSON(json: any): PutAdminIdpsByAliasRequestConfig {
    return PutAdminIdpsByAliasRequestConfigToJSONTyped(json, false);
}

export function PutAdminIdpsByAliasRequestConfigToJSONTyped(value?: PutAdminIdpsByAliasRequestConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
        'entityId': value['entityId'],
        'singleSignOnServiceUrl': value['singleSignOnServiceUrl'],
        'singleLogoutServiceUrl': value['singleLogoutServiceUrl'],
        'metadataDescriptorUrl': value['metadataDescriptorUrl'],
        'enabled': value['enabled'],
        'clientSecret': value['clientSecret'],
        'tokenUrl': value['tokenUrl'],
        'userInfoUrl': value['userInfoUrl'],
        'issuer': value['issuer'],
        'defaultScopes': value['defaultScopes'],
        'logoutUrl': value['logoutUrl'],
        'signatureAlgorithm': value['signatureAlgorithm'],
        'nameIdPolicyFormat': value['nameIdPolicyFormat'],
        'signingCertificate': value['signingCertificate'],
        'validateSignature': value['validateSignature'],
        'wantAuthnRequestsSigned': value['wantAuthnRequestsSigned'],
        'additionalConfig': value['additionalConfig'],
    };
}

