/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutAdminRolesByRoleName200Response
 */
export interface PutAdminRolesByRoleName200Response {
    /**
     * Whether the update was successful
     * @type {boolean}
     * @memberof PutAdminRolesByRoleName200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the PutAdminRolesByRoleName200Response interface.
 */
export function instanceOfPutAdminRolesByRoleName200Response(value: object): value is PutAdminRolesByRoleName200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function PutAdminRolesByRoleName200ResponseFromJSON(json: any): PutAdminRolesByRoleName200Response {
    return PutAdminRolesByRoleName200ResponseFromJSONTyped(json, false);
}

export function PutAdminRolesByRoleName200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminRolesByRoleName200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function PutAdminRolesByRoleName200ResponseToJSON(json: any): PutAdminRolesByRoleName200Response {
    return PutAdminRolesByRoleName200ResponseToJSONTyped(json, false);
}

export function PutAdminRolesByRoleName200ResponseToJSONTyped(value?: PutAdminRolesByRoleName200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

