/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutAdminRolesByRoleNameRequest
 */
export interface PutAdminRolesByRoleNameRequest {
    /**
     * Role description
     * @type {string}
     * @memberof PutAdminRolesByRoleNameRequest
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PutAdminRolesByRoleNameRequest
     */
    fhirScopes?: Array<string>;
}

/**
 * Check if a given object implements the PutAdminRolesByRoleNameRequest interface.
 */
export function instanceOfPutAdminRolesByRoleNameRequest(value: object): value is PutAdminRolesByRoleNameRequest {
    return true;
}

export function PutAdminRolesByRoleNameRequestFromJSON(json: any): PutAdminRolesByRoleNameRequest {
    return PutAdminRolesByRoleNameRequestFromJSONTyped(json, false);
}

export function PutAdminRolesByRoleNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminRolesByRoleNameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'fhirScopes': json['fhirScopes'] == null ? undefined : json['fhirScopes'],
    };
}

export function PutAdminRolesByRoleNameRequestToJSON(json: any): PutAdminRolesByRoleNameRequest {
    return PutAdminRolesByRoleNameRequestToJSONTyped(json, false);
}

export function PutAdminRolesByRoleNameRequestToJSONTyped(value?: PutAdminRolesByRoleNameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'fhirScopes': value['fhirScopes'],
    };
}

