/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutAdminLaunchContextsByUserIdNeedPatientBannerRequest
 */
export interface PutAdminLaunchContextsByUserIdNeedPatientBannerRequest {
    /**
     * Whether patient banner is required
     * @type {boolean}
     * @memberof PutAdminLaunchContextsByUserIdNeedPatientBannerRequest
     */
    needPatientBanner: boolean;
}

/**
 * Check if a given object implements the PutAdminLaunchContextsByUserIdNeedPatientBannerRequest interface.
 */
export function instanceOfPutAdminLaunchContextsByUserIdNeedPatientBannerRequest(value: object): value is PutAdminLaunchContextsByUserIdNeedPatientBannerRequest {
    if (!('needPatientBanner' in value) || value['needPatientBanner'] === undefined) return false;
    return true;
}

export function PutAdminLaunchContextsByUserIdNeedPatientBannerRequestFromJSON(json: any): PutAdminLaunchContextsByUserIdNeedPatientBannerRequest {
    return PutAdminLaunchContextsByUserIdNeedPatientBannerRequestFromJSONTyped(json, false);
}

export function PutAdminLaunchContextsByUserIdNeedPatientBannerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminLaunchContextsByUserIdNeedPatientBannerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'needPatientBanner': json['needPatientBanner'],
    };
}

export function PutAdminLaunchContextsByUserIdNeedPatientBannerRequestToJSON(json: any): PutAdminLaunchContextsByUserIdNeedPatientBannerRequest {
    return PutAdminLaunchContextsByUserIdNeedPatientBannerRequestToJSONTyped(json, false);
}

export function PutAdminLaunchContextsByUserIdNeedPatientBannerRequestToJSONTyped(value?: PutAdminLaunchContextsByUserIdNeedPatientBannerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'needPatientBanner': value['needPatientBanner'],
    };
}

