/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutAdminLaunchContextsByUserIdTenantRequest
 */
export interface PutAdminLaunchContextsByUserIdTenantRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof PutAdminLaunchContextsByUserIdTenantRequest
     */
    tenant: string;
}

/**
 * Check if a given object implements the PutAdminLaunchContextsByUserIdTenantRequest interface.
 */
export function instanceOfPutAdminLaunchContextsByUserIdTenantRequest(value: object): value is PutAdminLaunchContextsByUserIdTenantRequest {
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    return true;
}

export function PutAdminLaunchContextsByUserIdTenantRequestFromJSON(json: any): PutAdminLaunchContextsByUserIdTenantRequest {
    return PutAdminLaunchContextsByUserIdTenantRequestFromJSONTyped(json, false);
}

export function PutAdminLaunchContextsByUserIdTenantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAdminLaunchContextsByUserIdTenantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': json['tenant'],
    };
}

export function PutAdminLaunchContextsByUserIdTenantRequestToJSON(json: any): PutAdminLaunchContextsByUserIdTenantRequest {
    return PutAdminLaunchContextsByUserIdTenantRequestToJSONTyped(json, false);
}

export function PutAdminLaunchContextsByUserIdTenantRequestToJSONTyped(value?: PutAdminLaunchContextsByUserIdTenantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant': value['tenant'],
    };
}

