/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutFhirServersByServerIdMtlsRequest
 */
export interface PutFhirServersByServerIdMtlsRequest {
    /**
     * Whether to enable mTLS for this server
     * @type {boolean}
     * @memberof PutFhirServersByServerIdMtlsRequest
     */
    enabled: boolean;
}

/**
 * Check if a given object implements the PutFhirServersByServerIdMtlsRequest interface.
 */
export function instanceOfPutFhirServersByServerIdMtlsRequest(value: object): value is PutFhirServersByServerIdMtlsRequest {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    return true;
}

export function PutFhirServersByServerIdMtlsRequestFromJSON(json: any): PutFhirServersByServerIdMtlsRequest {
    return PutFhirServersByServerIdMtlsRequestFromJSONTyped(json, false);
}

export function PutFhirServersByServerIdMtlsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutFhirServersByServerIdMtlsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
    };
}

export function PutFhirServersByServerIdMtlsRequestToJSON(json: any): PutFhirServersByServerIdMtlsRequest {
    return PutFhirServersByServerIdMtlsRequestToJSONTyped(json, false);
}

export function PutFhirServersByServerIdMtlsRequestToJSONTyped(value?: PutFhirServersByServerIdMtlsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

