/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetFhirServers200ResponseServersInnerEndpoints } from './GetFhirServers200ResponseServersInnerEndpoints';
import {
    GetFhirServers200ResponseServersInnerEndpointsFromJSON,
    GetFhirServers200ResponseServersInnerEndpointsFromJSONTyped,
    GetFhirServers200ResponseServersInnerEndpointsToJSON,
    GetFhirServers200ResponseServersInnerEndpointsToJSONTyped,
} from './GetFhirServers200ResponseServersInnerEndpoints';

/**
 * 
 * @export
 * @interface PutFhirServersByServerId200ResponseServer
 */
export interface PutFhirServersByServerId200ResponseServer {
    /**
     * Server identifier used in URLs
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    id: string;
    /**
     * Human-readable server name
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    name: string;
    /**
     * Human-readable server name
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    displayName: string;
    /**
     * Updated server URL
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    url: string;
    /**
     * FHIR version supported by server
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    fhirVersion: string;
    /**
     * Server software version
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    serverVersion?: string;
    /**
     * Server software name
     * @type {string}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    serverName?: string;
    /**
     * Whether this server is supported
     * @type {boolean}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    supported: boolean;
    /**
     * 
     * @type {GetFhirServers200ResponseServersInnerEndpoints}
     * @memberof PutFhirServersByServerId200ResponseServer
     */
    endpoints: GetFhirServers200ResponseServersInnerEndpoints;
}

/**
 * Check if a given object implements the PutFhirServersByServerId200ResponseServer interface.
 */
export function instanceOfPutFhirServersByServerId200ResponseServer(value: object): value is PutFhirServersByServerId200ResponseServer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('fhirVersion' in value) || value['fhirVersion'] === undefined) return false;
    if (!('supported' in value) || value['supported'] === undefined) return false;
    if (!('endpoints' in value) || value['endpoints'] === undefined) return false;
    return true;
}

export function PutFhirServersByServerId200ResponseServerFromJSON(json: any): PutFhirServersByServerId200ResponseServer {
    return PutFhirServersByServerId200ResponseServerFromJSONTyped(json, false);
}

export function PutFhirServersByServerId200ResponseServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutFhirServersByServerId200ResponseServer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'displayName': json['displayName'],
        'url': json['url'],
        'fhirVersion': json['fhirVersion'],
        'serverVersion': json['serverVersion'] == null ? undefined : json['serverVersion'],
        'serverName': json['serverName'] == null ? undefined : json['serverName'],
        'supported': json['supported'],
        'endpoints': GetFhirServers200ResponseServersInnerEndpointsFromJSON(json['endpoints']),
    };
}

export function PutFhirServersByServerId200ResponseServerToJSON(json: any): PutFhirServersByServerId200ResponseServer {
    return PutFhirServersByServerId200ResponseServerToJSONTyped(json, false);
}

export function PutFhirServersByServerId200ResponseServerToJSONTyped(value?: PutFhirServersByServerId200ResponseServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'displayName': value['displayName'],
        'url': value['url'],
        'fhirVersion': value['fhirVersion'],
        'serverVersion': value['serverVersion'],
        'serverName': value['serverName'],
        'supported': value['supported'],
        'endpoints': GetFhirServers200ResponseServersInnerEndpointsToJSON(value['endpoints']),
    };
}

