/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutFhirServersByServerIdRequest
 */
export interface PutFhirServersByServerIdRequest {
    /**
     * New FHIR server base URL
     * @type {string}
     * @memberof PutFhirServersByServerIdRequest
     */
    url: string;
    /**
     * Optional custom name for the server
     * @type {string}
     * @memberof PutFhirServersByServerIdRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the PutFhirServersByServerIdRequest interface.
 */
export function instanceOfPutFhirServersByServerIdRequest(value: object): value is PutFhirServersByServerIdRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PutFhirServersByServerIdRequestFromJSON(json: any): PutFhirServersByServerIdRequest {
    return PutFhirServersByServerIdRequestFromJSONTyped(json, false);
}

export function PutFhirServersByServerIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutFhirServersByServerIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PutFhirServersByServerIdRequestToJSON(json: any): PutFhirServersByServerIdRequest {
    return PutFhirServersByServerIdRequestToJSONTyped(json, false);
}

export function PutFhirServersByServerIdRequestToJSONTyped(value?: PutFhirServersByServerIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'name': value['name'],
    };
}

