name: 'Cache OpenAPI Generator'
description: 'Cache OpenAPI Generator CLI tools and dependencies for faster builds'

inputs:
  cache-key-suffix:
    description: 'Additional suffix for cache key to allow multiple caches'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
  - name: Cache OpenAPI Generator CLI
    uses: actions/cache@v4
    with:
      path: |
        ~/.cache/bunx
        ~/.cache/openapi-generator-cli
        ~/.local/share/bunx
        ~/.npm/_cacache
        ~/.cache/bun
        node_modules/.cache
      key: ${{ runner.os }}-openapi-generator-${{ hashFiles('**/package.json', '**/bun.lock') }}${{ inputs.cache-key-suffix }}
      restore-keys: |
        ${{ runner.os }}-openapi-generator-${{ hashFiles('**/package.json') }}${{ inputs.cache-key-suffix }}
        ${{ runner.os }}-openapi-generator-

  - name: Pre-install OpenAPI Generator CLI
    shell: bash
    run: |
      echo "🔧 Pre-installing OpenAPI Generator CLI to cache..."
      # Pre-install the tool to ensure it's cached
      bunx @openapitools/openapi-generator-cli version
      echo "✅ OpenAPI Generator CLI cached successfully"
