/* tslint:disable */
/* eslint-disable */
/**
 * Proxy Smart
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1-alpha.202508151735.a205e19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetFhirServers500Response,
  PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response,
} from '../models/index';
import {
    GetFhirServers500ResponseFromJSON,
    GetFhirServers500ResponseToJSON,
    PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200ResponseFromJSON,
    PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200ResponseToJSON,
} from '../models/index';

export interface GetProxySmartBackendByServerNameByFhirVersionRequest {
    serverName: string;
    fhirVersion: string;
}

export interface PostProxySmartBackendByServerNameByFhirVersionCacheRefreshRequest {
    serverName: string;
    fhirVersion: string;
}

/**
 * 
 */
export class FhirApi extends runtime.BaseAPI {

    /**
     * Serve the content from the FHIR server base URL
     * FHIR Server Base URL
     */
    async getProxySmartBackendByServerNameByFhirVersionRaw(requestParameters: GetProxySmartBackendByServerNameByFhirVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['serverName'] == null) {
            throw new runtime.RequiredError(
                'serverName',
                'Required parameter "serverName" was null or undefined when calling getProxySmartBackendByServerNameByFhirVersion().'
            );
        }

        if (requestParameters['fhirVersion'] == null) {
            throw new runtime.RequiredError(
                'fhirVersion',
                'Required parameter "fhirVersion" was null or undefined when calling getProxySmartBackendByServerNameByFhirVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/proxy-smart-backend/{server_name}/{fhir_version}/`;
        urlPath = urlPath.replace(`{${"server_name"}}`, encodeURIComponent(String(requestParameters['serverName'])));
        urlPath = urlPath.replace(`{${"fhir_version"}}`, encodeURIComponent(String(requestParameters['fhirVersion'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Serve the content from the FHIR server base URL
     * FHIR Server Base URL
     */
    async getProxySmartBackendByServerNameByFhirVersion(requestParameters: GetProxySmartBackendByServerNameByFhirVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getProxySmartBackendByServerNameByFhirVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Clear and refresh the cached FHIR server information
     * Refresh FHIR Server Cache
     */
    async postProxySmartBackendByServerNameByFhirVersionCacheRefreshRaw(requestParameters: PostProxySmartBackendByServerNameByFhirVersionCacheRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response>> {
        if (requestParameters['serverName'] == null) {
            throw new runtime.RequiredError(
                'serverName',
                'Required parameter "serverName" was null or undefined when calling postProxySmartBackendByServerNameByFhirVersionCacheRefresh().'
            );
        }

        if (requestParameters['fhirVersion'] == null) {
            throw new runtime.RequiredError(
                'fhirVersion',
                'Required parameter "fhirVersion" was null or undefined when calling postProxySmartBackendByServerNameByFhirVersionCacheRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/proxy-smart-backend/{server_name}/{fhir_version}/cache/refresh`;
        urlPath = urlPath.replace(`{${"server_name"}}`, encodeURIComponent(String(requestParameters['serverName'])));
        urlPath = urlPath.replace(`{${"fhir_version"}}`, encodeURIComponent(String(requestParameters['fhirVersion'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200ResponseFromJSON(jsonValue));
    }

    /**
     * Clear and refresh the cached FHIR server information
     * Refresh FHIR Server Cache
     */
    async postProxySmartBackendByServerNameByFhirVersionCacheRefresh(requestParameters: PostProxySmartBackendByServerNameByFhirVersionCacheRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostProxySmartBackendByServerNameByFhirVersionCacheRefresh200Response> {
        const response = await this.postProxySmartBackendByServerNameByFhirVersionCacheRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
