/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR API
 * Healthcare administration API for SMART on FHIR applications
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteAdminSmartAppsByClientId200Response,
  GetAdminHealthcareUsers200ResponseInner,
  PostAdminHealthcareUsersRequest,
  PutAdminHealthcareUsersByUserIdRequest,
} from '../models/index';
import {
    DeleteAdminSmartAppsByClientId200ResponseFromJSON,
    DeleteAdminSmartAppsByClientId200ResponseToJSON,
    GetAdminHealthcareUsers200ResponseInnerFromJSON,
    GetAdminHealthcareUsers200ResponseInnerToJSON,
    PostAdminHealthcareUsersRequestFromJSON,
    PostAdminHealthcareUsersRequestToJSON,
    PutAdminHealthcareUsersByUserIdRequestFromJSON,
    PutAdminHealthcareUsersByUserIdRequestToJSON,
} from '../models/index';

export interface DeleteAdminHealthcareUsersByUserIdRequest {
    userId: string;
}

export interface GetAdminHealthcareUsersByUserIdRequest {
    userId: string;
}

export interface PostAdminHealthcareUsersOperationRequest {
    postAdminHealthcareUsersRequest: PostAdminHealthcareUsersRequest;
}

export interface PutAdminHealthcareUsersByUserIdOperationRequest {
    userId: string;
    putAdminHealthcareUsersByUserIdRequest: PutAdminHealthcareUsersByUserIdRequest;
}

/**
 * 
 */
export class HealthcareUsersApi extends runtime.BaseAPI {

    /**
     * Delete a healthcare user by userId
     * Delete Healthcare User
     */
    async deleteAdminHealthcareUsersByUserIdRaw(requestParameters: DeleteAdminHealthcareUsersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAdminSmartAppsByClientId200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteAdminHealthcareUsersByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/healthcare-users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAdminSmartAppsByClientId200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a healthcare user by userId
     * Delete Healthcare User
     */
    async deleteAdminHealthcareUsersByUserId(requestParameters: DeleteAdminHealthcareUsersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAdminSmartAppsByClientId200Response> {
        const response = await this.deleteAdminHealthcareUsersByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all healthcare users
     * List Healthcare Users
     */
    async getAdminHealthcareUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAdminHealthcareUsers200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/healthcare-users/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAdminHealthcareUsers200ResponseInnerFromJSON));
    }

    /**
     * Get all healthcare users
     * List Healthcare Users
     */
    async getAdminHealthcareUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAdminHealthcareUsers200ResponseInner>> {
        const response = await this.getAdminHealthcareUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a healthcare user by userId
     * Get Healthcare User
     */
    async getAdminHealthcareUsersByUserIdRaw(requestParameters: GetAdminHealthcareUsersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminHealthcareUsers200ResponseInner>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getAdminHealthcareUsersByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/healthcare-users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminHealthcareUsers200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Get a healthcare user by userId
     * Get Healthcare User
     */
    async getAdminHealthcareUsersByUserId(requestParameters: GetAdminHealthcareUsersByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminHealthcareUsers200ResponseInner> {
        const response = await this.getAdminHealthcareUsersByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new healthcare user
     * Create Healthcare User
     */
    async postAdminHealthcareUsersRaw(requestParameters: PostAdminHealthcareUsersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminHealthcareUsers200ResponseInner>> {
        if (requestParameters['postAdminHealthcareUsersRequest'] == null) {
            throw new runtime.RequiredError(
                'postAdminHealthcareUsersRequest',
                'Required parameter "postAdminHealthcareUsersRequest" was null or undefined when calling postAdminHealthcareUsers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/healthcare-users/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAdminHealthcareUsersRequestToJSON(requestParameters['postAdminHealthcareUsersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminHealthcareUsers200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Create a new healthcare user
     * Create Healthcare User
     */
    async postAdminHealthcareUsers(requestParameters: PostAdminHealthcareUsersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminHealthcareUsers200ResponseInner> {
        const response = await this.postAdminHealthcareUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a healthcare user by userId
     * Update Healthcare User
     */
    async putAdminHealthcareUsersByUserIdRaw(requestParameters: PutAdminHealthcareUsersByUserIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAdminHealthcareUsers200ResponseInner>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling putAdminHealthcareUsersByUserId().'
            );
        }

        if (requestParameters['putAdminHealthcareUsersByUserIdRequest'] == null) {
            throw new runtime.RequiredError(
                'putAdminHealthcareUsersByUserIdRequest',
                'Required parameter "putAdminHealthcareUsersByUserIdRequest" was null or undefined when calling putAdminHealthcareUsersByUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/healthcare-users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutAdminHealthcareUsersByUserIdRequestToJSON(requestParameters['putAdminHealthcareUsersByUserIdRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAdminHealthcareUsers200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Update a healthcare user by userId
     * Update Healthcare User
     */
    async putAdminHealthcareUsersByUserId(requestParameters: PutAdminHealthcareUsersByUserIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAdminHealthcareUsers200ResponseInner> {
        const response = await this.putAdminHealthcareUsersByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
