/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostAdminRolesRequest,
  PutAdminRolesByRoleNameRequest,
} from '../models/index';
import {
    PostAdminRolesRequestFromJSON,
    PostAdminRolesRequestToJSON,
    PutAdminRolesByRoleNameRequestFromJSON,
    PutAdminRolesByRoleNameRequestToJSON,
} from '../models/index';

export interface DeleteAdminRolesByRoleNameRequest {
    roleName: string;
}

export interface GetAdminRolesByRoleNameRequest {
    roleName: string;
}

export interface PostAdminRolesOperationRequest {
    postAdminRolesRequest: PostAdminRolesRequest;
}

export interface PutAdminRolesByRoleNameOperationRequest {
    roleName: string;
    putAdminRolesByRoleNameRequest: PutAdminRolesByRoleNameRequest;
}

/**
 * 
 */
export class RolesApi extends runtime.BaseAPI {

    /**
     * Delete a healthcare-specific role by name
     * Delete Healthcare Role
     */
    async deleteAdminRolesByRoleNameRaw(requestParameters: DeleteAdminRolesByRoleNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['roleName'] == null) {
            throw new runtime.RequiredError(
                'roleName',
                'Required parameter "roleName" was null or undefined when calling deleteAdminRolesByRoleName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/roles/{roleName}`;
        urlPath = urlPath.replace(`{${"roleName"}}`, encodeURIComponent(String(requestParameters['roleName'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a healthcare-specific role by name
     * Delete Healthcare Role
     */
    async deleteAdminRolesByRoleName(requestParameters: DeleteAdminRolesByRoleNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAdminRolesByRoleNameRaw(requestParameters, initOverrides);
    }

    /**
     * Get all roles
     * List All Roles
     */
    async getAdminRolesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/roles/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all roles
     * List All Roles
     */
    async getAdminRoles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAdminRolesRaw(initOverrides);
    }

    /**
     * Get a healthcare-specific role by name
     * Get Healthcare Role
     */
    async getAdminRolesByRoleNameRaw(requestParameters: GetAdminRolesByRoleNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['roleName'] == null) {
            throw new runtime.RequiredError(
                'roleName',
                'Required parameter "roleName" was null or undefined when calling getAdminRolesByRoleName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/roles/{roleName}`;
        urlPath = urlPath.replace(`{${"roleName"}}`, encodeURIComponent(String(requestParameters['roleName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a healthcare-specific role by name
     * Get Healthcare Role
     */
    async getAdminRolesByRoleName(requestParameters: GetAdminRolesByRoleNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getAdminRolesByRoleNameRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new healthcare-specific role
     * Create Healthcare Role
     */
    async postAdminRolesRaw(requestParameters: PostAdminRolesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postAdminRolesRequest'] == null) {
            throw new runtime.RequiredError(
                'postAdminRolesRequest',
                'Required parameter "postAdminRolesRequest" was null or undefined when calling postAdminRoles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/roles/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAdminRolesRequestToJSON(requestParameters['postAdminRolesRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new healthcare-specific role
     * Create Healthcare Role
     */
    async postAdminRoles(requestParameters: PostAdminRolesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postAdminRolesRaw(requestParameters, initOverrides);
    }

    /**
     * Update a healthcare-specific role by name
     * Update Healthcare Role
     */
    async putAdminRolesByRoleNameRaw(requestParameters: PutAdminRolesByRoleNameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['roleName'] == null) {
            throw new runtime.RequiredError(
                'roleName',
                'Required parameter "roleName" was null or undefined when calling putAdminRolesByRoleName().'
            );
        }

        if (requestParameters['putAdminRolesByRoleNameRequest'] == null) {
            throw new runtime.RequiredError(
                'putAdminRolesByRoleNameRequest',
                'Required parameter "putAdminRolesByRoleNameRequest" was null or undefined when calling putAdminRolesByRoleName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/roles/{roleName}`;
        urlPath = urlPath.replace(`{${"roleName"}}`, encodeURIComponent(String(requestParameters['roleName'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutAdminRolesByRoleNameRequestToJSON(requestParameters['putAdminRolesByRoleNameRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a healthcare-specific role by name
     * Update Healthcare Role
     */
    async putAdminRolesByRoleName(requestParameters: PutAdminRolesByRoleNameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putAdminRolesByRoleNameRaw(requestParameters, initOverrides);
    }

}
