/* tslint:disable */
/* eslint-disable */
/**
 * SMART on FHIR Proxy
 * SMART on FHIR Proxy + Healthcare Administration API using Keycloak and Elysia
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostFhirServersRequest,
  PutFhirServersByServerIdRequest,
} from '../models/index';
import {
    PostFhirServersRequestFromJSON,
    PostFhirServersRequestToJSON,
    PutFhirServersByServerIdRequestFromJSON,
    PutFhirServersByServerIdRequestToJSON,
} from '../models/index';

export interface GetFhirServersByServerNameRequest {
    serverName: string;
}

export interface PostFhirServersOperationRequest {
    postFhirServersRequest: PostFhirServersRequest;
}

export interface PutFhirServersByServerIdOperationRequest {
    serverId: string;
    putFhirServersByServerIdRequest: PutFhirServersByServerIdRequest;
}

/**
 * 
 */
export class ServersApi extends runtime.BaseAPI {

    /**
     * Get a list of all configured FHIR servers with their connection information and endpoints
     * List Available FHIR Servers
     */
    async getFhirServersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/fhir-servers/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a list of all configured FHIR servers with their connection information and endpoints
     * List Available FHIR Servers
     */
    async getFhirServers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getFhirServersRaw(initOverrides);
    }

    /**
     * Get detailed information about a specific FHIR server
     * Get Server Information
     */
    async getFhirServersByServerNameRaw(requestParameters: GetFhirServersByServerNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverName'] == null) {
            throw new runtime.RequiredError(
                'serverName',
                'Required parameter "serverName" was null or undefined when calling getFhirServersByServerName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/fhir-servers/{server_name}`;
        urlPath = urlPath.replace(`{${"server_name"}}`, encodeURIComponent(String(requestParameters['serverName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get detailed information about a specific FHIR server
     * Get Server Information
     */
    async getFhirServersByServerName(requestParameters: GetFhirServersByServerNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getFhirServersByServerNameRaw(requestParameters, initOverrides);
    }

    /**
     * Add a new FHIR server to the system by providing its base URL
     * Add New FHIR Server
     */
    async postFhirServersRaw(requestParameters: PostFhirServersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postFhirServersRequest'] == null) {
            throw new runtime.RequiredError(
                'postFhirServersRequest',
                'Required parameter "postFhirServersRequest" was null or undefined when calling postFhirServers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostFhirServersRequestToJSON(requestParameters['postFhirServersRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a new FHIR server to the system by providing its base URL
     * Add New FHIR Server
     */
    async postFhirServers(requestParameters: PostFhirServersOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postFhirServersRaw(requestParameters, initOverrides);
    }

    /**
     * Update an existing FHIR server by providing its new base URL
     * Update FHIR Server
     */
    async putFhirServersByServerIdRaw(requestParameters: PutFhirServersByServerIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['serverId'] == null) {
            throw new runtime.RequiredError(
                'serverId',
                'Required parameter "serverId" was null or undefined when calling putFhirServersByServerId().'
            );
        }

        if (requestParameters['putFhirServersByServerIdRequest'] == null) {
            throw new runtime.RequiredError(
                'putFhirServersByServerIdRequest',
                'Required parameter "putFhirServersByServerIdRequest" was null or undefined when calling putFhirServersByServerId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/fhir-servers/{serverId}`;
        urlPath = urlPath.replace(`{${"serverId"}}`, encodeURIComponent(String(requestParameters['serverId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutFhirServersByServerIdRequestToJSON(requestParameters['putFhirServersByServerIdRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update an existing FHIR server by providing its new base URL
     * Update FHIR Server
     */
    async putFhirServersByServerId(requestParameters: PutFhirServersByServerIdOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.putFhirServersByServerIdRaw(requestParameters, initOverrides);
    }

}
