name: 'Setup Python with AI Dependencies (UV)'
description: 'Setup Python with uv for ultra-fast dependency installation and caching'

inputs:
  python-version:
    description: 'Python version to setup'
    required: false
    default: '3.11'
  cache-dependency-path:
    description: 'Path to dependency file for cache key'
    required: false
    default: 'scripts/requirements.txt'

runs:
  using: 'composite'
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v4
    with:
      # Install a specific version or use the latest
      version: "latest"

  - name: Setup Python with uv
    shell: bash
    run: |
      echo "🐍 Setting up Python ${{ inputs.python-version }} with uv..."
      uv python install ${{ inputs.python-version }}
      uv python pin ${{ inputs.python-version }}
      echo "✅ Python ${{ inputs.python-version }} installed with uv"

  - name: Cache uv dependencies
    uses: actions/cache@v4
    with:
      path: |
        ~/.cache/uv
        scripts/.venv
      key: ${{ runner.os }}-uv-python-${{ inputs.python-version }}-${{ hashFiles(inputs.cache-dependency-path) }}
      restore-keys: |
        ${{ runner.os }}-uv-python-${{ inputs.python-version }}-
        ${{ runner.os }}-uv-python-

  - name: Install AI dependencies with uv
    shell: bash
    run: |
      echo "📦 Installing Python AI dependencies with uv (ultra-fast!)..."

      # Change to scripts directory
      cd scripts

      # Create virtual environment if it doesn't exist
      if [ ! -d ".venv" ]; then
        uv venv
      fi

      # Install from requirements.txt in the current directory (scripts/)
      echo "📋 Installing dependencies from requirements.txt"
      if [ -f "requirements.txt" ]; then
        uv pip install -r requirements.txt
      else
        echo "❌ Could not find requirements.txt in scripts/ directory" >&2
        ls -la
        exit 1
      fi

      # Make sure the virtual environment is activated for subsequent steps
      echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
      echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      echo "✅ Python AI dependencies installed with uv and cached"
