name: AI Build & Test

on:
  push:
    branches:
      - "ai/dev/*"
  workflow_call:
    inputs:
      run_tests:
        description: "Whether to run tests"
        required: false
        type: boolean
        default: true
      fail_on_test_failure:
        description: "Whether to fail the workflow if tests fail"
        required: false
        type: boolean
        default: true
    outputs:
      backend_success:
        description: "Whether backend build was successful"
        value: ${{ jobs.backend.outputs.backend_success }}
      frontend_success:
        description: "Whether frontend build was successful"
        value: ${{ jobs.frontend.outputs.frontend_success }}
      backend_tests_success:
        description: "Whether backend tests were successful"
        value: ${{ jobs.backend.outputs.backend_tests_success }}
      frontend_tests_success:
        description: "Whether frontend tests were successful"
        value: ${{ jobs.frontend.outputs.frontend_tests_success }}
    secrets:
      APP_ID:
        required: false
      APP_PRIVATE_KEY:
        required: false
      OPENAI_API_KEY:
        required: false

jobs:
  backend:
    name: Backend
    uses: ./.github/workflows/ai-build-test-backend.yml
    with:
      run_tests: ${{ inputs.run_tests || true }}
      fail_on_test_failure: ${{ inputs.fail_on_test_failure || true }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  frontend:
    name: Frontend
    needs: backend
    if: ${{ needs.backend.outputs.backend_success == 'true' }}
    uses: ./.github/workflows/ai-build-test-frontend.yml
    with:
      run_tests: ${{ inputs.run_tests || true }}
      fail_on_test_failure: ${{ inputs.fail_on_test_failure || true }}
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
