name: Alpha Release

on:
  push:
    branches: [develop]
    paths-ignore:
      - 'ui/src/lib/api-client/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: releases
  cancel-in-progress: false

jobs:
  alpha-release:
    name: Alpha Release
    # Only run if the last commit is not a release commit to avoid infinite loops
    if: ${{ !contains(github.event.head_commit.message, '🔄 Update version') && !contains(github.event.head_commit.message, '🤖 Update client APIs') && !contains(github.event.head_commit.message, 'Alpha release') && !contains(github.event.head_commit.message, '🚀') && !contains(github.event.head_commit.message, 'proxy-smart-releaser') }}
    uses: ./.github/workflows/release-orchestrator.yml
    with:
      release_type: 'alpha'
      source_branch: 'develop'
      target_branch: 'develop'
      should_bump_version: true
      is_prerelease: true
      commit_limit: 10
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  # Deploy after successful release
  deploy-alpha:
    name: Deploy Alpha to Fly.io
    needs: [alpha-release]
    uses: ./.github/workflows/deployment-strategy.yml
    with:
      deployment_stage: 'alpha'
      app_version: ${{ needs.alpha-release.outputs.version }}
      source_branch: 'develop'
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      ALPHA_DB_PASSWORD: ${{ secrets.ALPHA_DB_PASSWORD }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  # Test the deployed alpha application
  test-alpha-deployment:
    name: Test Alpha Deployment
    needs: [alpha-release, deploy-alpha]
    uses: ./.github/workflows/testing-strategy.yml
    with:
      test_stage: 'alpha'
      deployment_target: ${{ needs.deploy-alpha.outputs.deployment_target }}
      fhir_server_url: ${{ needs.deploy-alpha.outputs.fhir_server_url }}
      keycloak_url: ${{ needs.deploy-alpha.outputs.keycloak_url }}
      app_version: ${{ needs.alpha-release.outputs.version }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
